// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	common "social-network/shared/gen-go/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName         string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Avatar            int64                  `protobuf:"varint,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	About             string                 `protobuf:"bytes,7,opt,name=about,proto3" json:"about,omitempty"`
	Public            bool                   `protobuf:"varint,8,opt,name=public,proto3" json:"public,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FollowersCount    int64                  `protobuf:"varint,10,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount    int64                  `protobuf:"varint,11,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	GroupsCount       int64                  `protobuf:"varint,12,opt,name=groups_count,json=groupsCount,proto3" json:"groups_count,omitempty"`
	OwnedGroupsCount  int64                  `protobuf:"varint,13,opt,name=owned_groups_count,json=ownedGroupsCount,proto3" json:"owned_groups_count,omitempty"`
	ViewerIsFollowing bool                   `protobuf:"varint,14,opt,name=viewer_is_following,json=viewerIsFollowing,proto3" json:"viewer_is_following,omitempty"`
	OwnProfile        bool                   `protobuf:"varint,15,opt,name=own_profile,json=ownProfile,proto3" json:"own_profile,omitempty"`
	IsPending         bool                   `protobuf:"varint,16,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfileResponse) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UserProfileResponse) GetAvatar() int64 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

func (x *UserProfileResponse) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *UserProfileResponse) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *UserProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfileResponse) GetFollowersCount() int64 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *UserProfileResponse) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *UserProfileResponse) GetGroupsCount() int64 {
	if x != nil {
		return x.GroupsCount
	}
	return 0
}

func (x *UserProfileResponse) GetOwnedGroupsCount() int64 {
	if x != nil {
		return x.OwnedGroupsCount
	}
	return 0
}

func (x *UserProfileResponse) GetViewerIsFollowing() bool {
	if x != nil {
		return x.ViewerIsFollowing
	}
	return false
}

func (x *UserProfileResponse) GetOwnProfile() bool {
	if x != nil {
		return x.OwnProfile
	}
	return false
}

func (x *UserProfileResponse) GetIsPending() bool {
	if x != nil {
		return x.IsPending
	}
	return false
}

// REGISTER USER
type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Avatar        int64                  `protobuf:"varint,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	About         string                 `protobuf:"bytes,6,opt,name=about,proto3" json:"about,omitempty"`
	Public        bool                   `protobuf:"varint,7,opt,name=public,proto3" json:"public,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterUserRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *RegisterUserRequest) GetAvatar() int64 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

func (x *RegisterUserRequest) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *RegisterUserRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LOGIN
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// UPDATE PASSWORD
type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// UPDATE USER EMAIL
type UpdateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEmailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// GET FOLLOWERS
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

func (x *Pagination) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// FOLLOW USER
type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	TargetUserId  int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

func (x *FollowUserRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowUserRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type FollowUserResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsPending         bool                   `protobuf:"varint,1,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	ViewerIsFollowing bool                   `protobuf:"varint,2,opt,name=viewer_is_following,json=viewerIsFollowing,proto3" json:"viewer_is_following,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *FollowUserResponse) GetIsPending() bool {
	if x != nil {
		return x.IsPending
	}
	return false
}

func (x *FollowUserResponse) GetViewerIsFollowing() bool {
	if x != nil {
		return x.ViewerIsFollowing
	}
	return false
}

type HandleFollowRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Accept        bool                   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFollowRequestRequest) Reset() {
	*x = HandleFollowRequestRequest{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFollowRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFollowRequestRequest) ProtoMessage() {}

func (x *HandleFollowRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFollowRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleFollowRequestRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *HandleFollowRequestRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HandleFollowRequestRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *HandleFollowRequestRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type IsFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	TargetUserId  int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

func (x *IsFollowingRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *IsFollowingRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// GROUPS
type Group struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupOwnerId     int64                  `protobuf:"varint,2,opt,name=group_owner_id,json=groupOwnerId,proto3" json:"group_owner_id,omitempty"`
	GroupTitle       string                 `protobuf:"bytes,3,opt,name=group_title,json=groupTitle,proto3" json:"group_title,omitempty"`
	GroupDescription string                 `protobuf:"bytes,4,opt,name=group_description,json=groupDescription,proto3" json:"group_description,omitempty"`
	GroupImage       string                 `protobuf:"bytes,5,opt,name=group_image,json=groupImage,proto3" json:"group_image,omitempty"`
	MembersCount     int32                  `protobuf:"varint,6,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	IsMember         bool                   `protobuf:"varint,7,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	IsOwner          bool                   `protobuf:"varint,8,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	IsPending        bool                   `protobuf:"varint,9,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{10}
}

func (x *Group) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Group) GetGroupOwnerId() int64 {
	if x != nil {
		return x.GroupOwnerId
	}
	return 0
}

func (x *Group) GetGroupTitle() string {
	if x != nil {
		return x.GroupTitle
	}
	return ""
}

func (x *Group) GetGroupDescription() string {
	if x != nil {
		return x.GroupDescription
	}
	return ""
}

func (x *Group) GetGroupImage() string {
	if x != nil {
		return x.GroupImage
	}
	return ""
}

func (x *Group) GetMembersCount() int32 {
	if x != nil {
		return x.MembersCount
	}
	return 0
}

func (x *Group) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *Group) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

func (x *Group) GetIsPending() bool {
	if x != nil {
		return x.IsPending
	}
	return false
}

type GroupArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupArr      []*Group               `protobuf:"bytes,1,rep,name=group_arr,json=groupArr,proto3" json:"group_arr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupArr) Reset() {
	*x = GroupArr{}
	mi := &file_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupArr) ProtoMessage() {}

func (x *GroupArr) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupArr.ProtoReflect.Descriptor instead.
func (*GroupArr) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{11}
}

func (x *GroupArr) GetGroupArr() []*Group {
	if x != nil {
		return x.GroupArr
	}
	return nil
}

type GeneralGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralGroupRequest) Reset() {
	*x = GeneralGroupRequest{}
	mi := &file_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralGroupRequest) ProtoMessage() {}

func (x *GeneralGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralGroupRequest.ProtoReflect.Descriptor instead.
func (*GeneralGroupRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{12}
}

func (x *GeneralGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GeneralGroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembersRequest) Reset() {
	*x = GroupMembersRequest{}
	mi := &file_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersRequest) ProtoMessage() {}

func (x *GroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersRequest.ProtoReflect.Descriptor instead.
func (*GroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{13}
}

func (x *GroupMembersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMembersRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GroupMembersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GroupUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        int64                  `protobuf:"varint,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GroupRole     string                 `protobuf:"bytes,4,opt,name=group_role,json=groupRole,proto3" json:"group_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUser) Reset() {
	*x = GroupUser{}
	mi := &file_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUser) ProtoMessage() {}

func (x *GroupUser) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUser.ProtoReflect.Descriptor instead.
func (*GroupUser) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{14}
}

func (x *GroupUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupUser) GetAvatar() int64 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

func (x *GroupUser) GetGroupRole() string {
	if x != nil {
		return x.GroupRole
	}
	return ""
}

type GroupUserArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupUserArr  []*GroupUser           `protobuf:"bytes,1,rep,name=group_user_arr,json=groupUserArr,proto3" json:"group_user_arr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUserArr) Reset() {
	*x = GroupUserArr{}
	mi := &file_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUserArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUserArr) ProtoMessage() {}

func (x *GroupUserArr) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUserArr.ProtoReflect.Descriptor instead.
func (*GroupUserArr) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{15}
}

func (x *GroupUserArr) GetGroupUserArr() []*GroupUser {
	if x != nil {
		return x.GroupUserArr
	}
	return nil
}

type GroupSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSearchRequest) Reset() {
	*x = GroupSearchRequest{}
	mi := &file_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSearchRequest) ProtoMessage() {}

func (x *GroupSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSearchRequest.ProtoReflect.Descriptor instead.
func (*GroupSearchRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{16}
}

func (x *GroupSearchRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *GroupSearchRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GroupSearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type InviteToGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviterId     int64                  `protobuf:"varint,1,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	InvitedId     int64                  `protobuf:"varint,2,opt,name=invited_id,json=invitedId,proto3" json:"invited_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToGroupRequest) Reset() {
	*x = InviteToGroupRequest{}
	mi := &file_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToGroupRequest) ProtoMessage() {}

func (x *InviteToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToGroupRequest.ProtoReflect.Descriptor instead.
func (*InviteToGroupRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{17}
}

func (x *InviteToGroupRequest) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *InviteToGroupRequest) GetInvitedId() int64 {
	if x != nil {
		return x.InvitedId
	}
	return 0
}

func (x *InviteToGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupJoinRequest) Reset() {
	*x = GroupJoinRequest{}
	mi := &file_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinRequest) ProtoMessage() {}

func (x *GroupJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinRequest.ProtoReflect.Descriptor instead.
func (*GroupJoinRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{18}
}

func (x *GroupJoinRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupJoinRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type HandleGroupInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InvitedId     int64                  `protobuf:"varint,2,opt,name=invited_id,json=invitedId,proto3" json:"invited_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGroupInviteRequest) Reset() {
	*x = HandleGroupInviteRequest{}
	mi := &file_users_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGroupInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGroupInviteRequest) ProtoMessage() {}

func (x *HandleGroupInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGroupInviteRequest.ProtoReflect.Descriptor instead.
func (*HandleGroupInviteRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{19}
}

func (x *HandleGroupInviteRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *HandleGroupInviteRequest) GetInvitedId() int64 {
	if x != nil {
		return x.InvitedId
	}
	return 0
}

func (x *HandleGroupInviteRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type HandleJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleJoinRequest) Reset() {
	*x = HandleJoinRequest{}
	mi := &file_users_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleJoinRequest) ProtoMessage() {}

func (x *HandleJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleJoinRequest.ProtoReflect.Descriptor instead.
func (*HandleJoinRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{20}
}

func (x *HandleJoinRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *HandleJoinRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *HandleJoinRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *HandleJoinRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RemoveFromGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberId      int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromGroupRequest) Reset() {
	*x = RemoveFromGroupRequest{}
	mi := &file_users_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromGroupRequest) ProtoMessage() {}

func (x *RemoveFromGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromGroupRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveFromGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RemoveFromGroupRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *RemoveFromGroupRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type CreateGroupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OwnerId          int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	GroupTitle       string                 `protobuf:"bytes,2,opt,name=group_title,json=groupTitle,proto3" json:"group_title,omitempty"`
	GroupDescription string                 `protobuf:"bytes,3,opt,name=group_description,json=groupDescription,proto3" json:"group_description,omitempty"`
	GroupImage       string                 `protobuf:"bytes,4,opt,name=group_image,json=groupImage,proto3" json:"group_image,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_users_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{22}
}

func (x *CreateGroupRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateGroupRequest) GetGroupTitle() string {
	if x != nil {
		return x.GroupTitle
	}
	return ""
}

func (x *CreateGroupRequest) GetGroupDescription() string {
	if x != nil {
		return x.GroupDescription
	}
	return ""
}

func (x *CreateGroupRequest) GetGroupImage() string {
	if x != nil {
		return x.GroupImage
	}
	return ""
}

// BASIC USER INFO
type UserBasicInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Avatar        int64                  `protobuf:"varint,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PublicProfile bool                   `protobuf:"varint,4,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBasicInfoResponse) Reset() {
	*x = UserBasicInfoResponse{}
	mi := &file_users_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBasicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfoResponse) ProtoMessage() {}

func (x *UserBasicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfoResponse.ProtoReflect.Descriptor instead.
func (*UserBasicInfoResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{23}
}

func (x *UserBasicInfoResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserBasicInfoResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserBasicInfoResponse) GetAvatar() int64 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

func (x *UserBasicInfoResponse) GetPublicProfile() bool {
	if x != nil {
		return x.PublicProfile
	}
	return false
}

// GET USER PROFILE
type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_users_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserProfileRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type UserSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSearchRequest) Reset() {
	*x = UserSearchRequest{}
	mi := &file_users_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchRequest) ProtoMessage() {}

func (x *UserSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchRequest.ProtoReflect.Descriptor instead.
func (*UserSearchRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{25}
}

func (x *UserSearchRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *UserSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Avatar        int64                  `protobuf:"varint,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	About         string                 `protobuf:"bytes,7,opt,name=about,proto3" json:"about,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_users_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateProfileRequest) GetAvatar() int64 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

func (x *UpdateProfileRequest) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

type UpdateProfilePrivacyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Public        bool                   `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfilePrivacyRequest) Reset() {
	*x = UpdateProfilePrivacyRequest{}
	mi := &file_users_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfilePrivacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfilePrivacyRequest) ProtoMessage() {}

func (x *UpdateProfilePrivacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfilePrivacyRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfilePrivacyRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateProfilePrivacyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfilePrivacyRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xda\x04\n" +
	"\x13UserProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\x03R\x06avatar\x12\x14\n" +
	"\x05about\x18\a \x01(\tR\x05about\x12\x16\n" +
	"\x06public\x18\b \x01(\bR\x06public\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12'\n" +
	"\x0ffollowers_count\x18\n" +
	" \x01(\x03R\x0efollowersCount\x12'\n" +
	"\x0ffollowing_count\x18\v \x01(\x03R\x0efollowingCount\x12!\n" +
	"\fgroups_count\x18\f \x01(\x03R\vgroupsCount\x12,\n" +
	"\x12owned_groups_count\x18\r \x01(\x03R\x10ownedGroupsCount\x12.\n" +
	"\x13viewer_is_following\x18\x0e \x01(\bR\x11viewerIsFollowing\x12\x1f\n" +
	"\vown_profile\x18\x0f \x01(\bR\n" +
	"ownProfile\x12\x1d\n" +
	"\n" +
	"is_pending\x18\x10 \x01(\bR\tisPending\"\xa5\x02\n" +
	"\x13RegisterUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\x03R\x06avatar\x12\x14\n" +
	"\x05about\x18\x06 \x01(\tR\x05about\x12\x16\n" +
	"\x06public\x18\a \x01(\bR\x06public\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\t \x01(\tR\bpassword\"J\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"v\n" +
	"\x15UpdatePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"C\n" +
	"\x12UpdateEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"S\n" +
	"\n" +
	"Pagination\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Z\n" +
	"\x11FollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"c\n" +
	"\x12FollowUserResponse\x12\x1d\n" +
	"\n" +
	"is_pending\x18\x01 \x01(\bR\tisPending\x12.\n" +
	"\x13viewer_is_following\x18\x02 \x01(\bR\x11viewerIsFollowing\"p\n" +
	"\x1aHandleFollowRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\"[\n" +
	"\x12IsFollowingRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"\xb3\x02\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12$\n" +
	"\x0egroup_owner_id\x18\x02 \x01(\x03R\fgroupOwnerId\x12\x1f\n" +
	"\vgroup_title\x18\x03 \x01(\tR\n" +
	"groupTitle\x12+\n" +
	"\x11group_description\x18\x04 \x01(\tR\x10groupDescription\x12\x1f\n" +
	"\vgroup_image\x18\x05 \x01(\tR\n" +
	"groupImage\x12#\n" +
	"\rmembers_count\x18\x06 \x01(\x05R\fmembersCount\x12\x1b\n" +
	"\tis_member\x18\a \x01(\bR\bisMember\x12\x19\n" +
	"\bis_owner\x18\b \x01(\bR\aisOwner\x12\x1d\n" +
	"\n" +
	"is_pending\x18\t \x01(\bR\tisPending\"5\n" +
	"\bGroupArr\x12)\n" +
	"\tgroup_arr\x18\x01 \x03(\v2\f.users.GroupR\bgroupArr\"I\n" +
	"\x13GeneralGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"w\n" +
	"\x13GroupMembersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"w\n" +
	"\tGroupUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\x03R\x06avatar\x12\x1d\n" +
	"\n" +
	"group_role\x18\x04 \x01(\tR\tgroupRole\"F\n" +
	"\fGroupUserArr\x126\n" +
	"\x0egroup_user_arr\x18\x01 \x03(\v2\x10.users.GroupUserR\fgroupUserArr\"|\n" +
	"\x12GroupSearchRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"o\n" +
	"\x14InviteToGroupRequest\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x01 \x01(\x03R\tinviterId\x12\x1d\n" +
	"\n" +
	"invited_id\x18\x02 \x01(\x03R\tinvitedId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\"P\n" +
	"\x10GroupJoinRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\"p\n" +
	"\x18HandleGroupInviteRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"invited_id\x18\x02 \x01(\x03R\tinvitedId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\"\x88\x01\n" +
	"\x11HandleJoinRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\"k\n" +
	"\x16RemoveFromGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\"\x9e\x01\n" +
	"\x12CreateGroupRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x1f\n" +
	"\vgroup_title\x18\x02 \x01(\tR\n" +
	"groupTitle\x12+\n" +
	"\x11group_description\x18\x03 \x01(\tR\x10groupDescription\x12\x1f\n" +
	"\vgroup_image\x18\x04 \x01(\tR\n" +
	"groupImage\"\x8c\x01\n" +
	"\x15UserBasicInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\x03R\x06avatar\x12%\n" +
	"\x0epublic_profile\x18\x04 \x01(\bR\rpublicProfile\"S\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\"J\n" +
	"\x11UserSearchRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xf5\x01\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\x03R\x06avatar\x12\x14\n" +
	"\x05about\x18\a \x01(\tR\x05about\"N\n" +
	"\x1bUpdateProfilePrivacyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public2\xde\x10\n" +
	"\vUserService\x128\n" +
	"\fRegisterUser\x12\x1a.users.RegisterUserRequest\x1a\f.common.User\x12.\n" +
	"\tLoginUser\x12\x13.users.LoginRequest\x1a\f.common.User\x12J\n" +
	"\x12UpdateUserPassword\x12\x1c.users.UpdatePasswordRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x0fUpdateUserEmail\x12\x19.users.UpdateEmailRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x15GetFollowersPaginated\x12\x11.users.Pagination\x1a\x11.common.ListUsers\x12=\n" +
	"\x15GetFollowingPaginated\x12\x11.users.Pagination\x1a\x11.common.ListUsers\x12A\n" +
	"\n" +
	"FollowUser\x12\x18.users.FollowUserRequest\x1a\x19.users.FollowUserResponse\x12D\n" +
	"\fUnFollowUser\x12\x18.users.FollowUserRequest\x1a\x1a.google.protobuf.BoolValue\x12P\n" +
	"\x13HandleFollowRequest\x12!.users.HandleFollowRequestRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x0fGetFollowingIds\x12\x1b.google.protobuf.Int64Value\x1a\x10.common.Int64Arr\x12F\n" +
	"\x14GetFollowSuggestions\x12\x1b.google.protobuf.Int64Value\x1a\x11.common.ListUsers\x12C\n" +
	"\vIsFollowing\x12\x18.users.FollowUserRequest\x1a\x1a.google.protobuf.BoolValue\x12M\n" +
	"\x15AreFollowingEachOther\x12\x18.users.FollowUserRequest\x1a\x1a.google.protobuf.BoolValue\x12;\n" +
	"\x15GetAllGroupsPaginated\x12\x11.users.Pagination\x1a\x0f.users.GroupArr\x12<\n" +
	"\x16GetUserGroupsPaginated\x12\x11.users.Pagination\x1a\x0f.users.GroupArr\x128\n" +
	"\fGetGroupInfo\x12\x1a.users.GeneralGroupRequest\x1a\f.users.Group\x12B\n" +
	"\x0fGetGroupMembers\x12\x1a.users.GroupMembersRequest\x1a\x13.users.GroupUserArr\x12:\n" +
	"\fSearchGroups\x12\x19.users.GroupSearchRequest\x1a\x0f.users.GroupArr\x12D\n" +
	"\rInviteToGroup\x12\x1b.users.InviteToGroupRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\rIsGroupMember\x12\x1a.users.GeneralGroupRequest\x1a\x1a.google.protobuf.BoolValue\x12K\n" +
	"\x18RequestJoinGroupOrCancel\x12\x17.users.GroupJoinRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x14RespondToGroupInvite\x12\x1f.users.HandleGroupInviteRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x16HandleGroupJoinRequest\x12\x18.users.HandleJoinRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"LeaveGroup\x12\x1a.users.GeneralGroupRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\vCreateGroup\x12\x19.users.CreateGroupRequest\x1a\x1b.google.protobuf.Int64Value\x12=\n" +
	"\x10GetBasicUserInfo\x12\x1b.google.protobuf.Int64Value\x1a\f.common.User\x12<\n" +
	"\x15GetBatchBasicUserInfo\x12\x10.common.Int64Arr\x1a\x11.common.ListUsers\x12J\n" +
	"\x0eGetUserProfile\x12\x1c.users.GetUserProfileRequest\x1a\x1a.users.UserProfileResponse\x12:\n" +
	"\vSearchUsers\x12\x18.users.UserSearchRequest\x1a\x11.common.ListUsers\x12L\n" +
	"\x11UpdateUserProfile\x12\x1b.users.UpdateProfileRequest\x1a\x1a.users.UserProfileResponse\x12R\n" +
	"\x14UpdateProfilePrivacy\x12\".users.UpdateProfilePrivacyRequest\x1a\x16.google.protobuf.EmptyB*Z(social-network/shared/gen-go/users;usersb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_users_proto_goTypes = []any{
	(*UserProfileResponse)(nil),         // 0: users.UserProfileResponse
	(*RegisterUserRequest)(nil),         // 1: users.RegisterUserRequest
	(*LoginRequest)(nil),                // 2: users.LoginRequest
	(*UpdatePasswordRequest)(nil),       // 3: users.UpdatePasswordRequest
	(*UpdateEmailRequest)(nil),          // 4: users.UpdateEmailRequest
	(*Pagination)(nil),                  // 5: users.Pagination
	(*FollowUserRequest)(nil),           // 6: users.FollowUserRequest
	(*FollowUserResponse)(nil),          // 7: users.FollowUserResponse
	(*HandleFollowRequestRequest)(nil),  // 8: users.HandleFollowRequestRequest
	(*IsFollowingRequest)(nil),          // 9: users.IsFollowingRequest
	(*Group)(nil),                       // 10: users.Group
	(*GroupArr)(nil),                    // 11: users.GroupArr
	(*GeneralGroupRequest)(nil),         // 12: users.GeneralGroupRequest
	(*GroupMembersRequest)(nil),         // 13: users.GroupMembersRequest
	(*GroupUser)(nil),                   // 14: users.GroupUser
	(*GroupUserArr)(nil),                // 15: users.GroupUserArr
	(*GroupSearchRequest)(nil),          // 16: users.GroupSearchRequest
	(*InviteToGroupRequest)(nil),        // 17: users.InviteToGroupRequest
	(*GroupJoinRequest)(nil),            // 18: users.GroupJoinRequest
	(*HandleGroupInviteRequest)(nil),    // 19: users.HandleGroupInviteRequest
	(*HandleJoinRequest)(nil),           // 20: users.HandleJoinRequest
	(*RemoveFromGroupRequest)(nil),      // 21: users.RemoveFromGroupRequest
	(*CreateGroupRequest)(nil),          // 22: users.CreateGroupRequest
	(*UserBasicInfoResponse)(nil),       // 23: users.UserBasicInfoResponse
	(*GetUserProfileRequest)(nil),       // 24: users.GetUserProfileRequest
	(*UserSearchRequest)(nil),           // 25: users.UserSearchRequest
	(*UpdateProfileRequest)(nil),        // 26: users.UpdateProfileRequest
	(*UpdateProfilePrivacyRequest)(nil), // 27: users.UpdateProfilePrivacyRequest
	(*timestamppb.Timestamp)(nil),       // 28: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil),       // 29: google.protobuf.Int64Value
	(*common.Int64Arr)(nil),             // 30: common.Int64Arr
	(*common.User)(nil),                 // 31: common.User
	(*emptypb.Empty)(nil),               // 32: google.protobuf.Empty
	(*common.ListUsers)(nil),            // 33: common.ListUsers
	(*wrapperspb.BoolValue)(nil),        // 34: google.protobuf.BoolValue
}
var file_users_proto_depIdxs = []int32{
	28, // 0: users.UserProfileResponse.date_of_birth:type_name -> google.protobuf.Timestamp
	28, // 1: users.UserProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	28, // 2: users.RegisterUserRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	10, // 3: users.GroupArr.group_arr:type_name -> users.Group
	14, // 4: users.GroupUserArr.group_user_arr:type_name -> users.GroupUser
	28, // 5: users.UpdateProfileRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	1,  // 6: users.UserService.RegisterUser:input_type -> users.RegisterUserRequest
	2,  // 7: users.UserService.LoginUser:input_type -> users.LoginRequest
	3,  // 8: users.UserService.UpdateUserPassword:input_type -> users.UpdatePasswordRequest
	4,  // 9: users.UserService.UpdateUserEmail:input_type -> users.UpdateEmailRequest
	5,  // 10: users.UserService.GetFollowersPaginated:input_type -> users.Pagination
	5,  // 11: users.UserService.GetFollowingPaginated:input_type -> users.Pagination
	6,  // 12: users.UserService.FollowUser:input_type -> users.FollowUserRequest
	6,  // 13: users.UserService.UnFollowUser:input_type -> users.FollowUserRequest
	8,  // 14: users.UserService.HandleFollowRequest:input_type -> users.HandleFollowRequestRequest
	29, // 15: users.UserService.GetFollowingIds:input_type -> google.protobuf.Int64Value
	29, // 16: users.UserService.GetFollowSuggestions:input_type -> google.protobuf.Int64Value
	6,  // 17: users.UserService.IsFollowing:input_type -> users.FollowUserRequest
	6,  // 18: users.UserService.AreFollowingEachOther:input_type -> users.FollowUserRequest
	5,  // 19: users.UserService.GetAllGroupsPaginated:input_type -> users.Pagination
	5,  // 20: users.UserService.GetUserGroupsPaginated:input_type -> users.Pagination
	12, // 21: users.UserService.GetGroupInfo:input_type -> users.GeneralGroupRequest
	13, // 22: users.UserService.GetGroupMembers:input_type -> users.GroupMembersRequest
	16, // 23: users.UserService.SearchGroups:input_type -> users.GroupSearchRequest
	17, // 24: users.UserService.InviteToGroup:input_type -> users.InviteToGroupRequest
	12, // 25: users.UserService.IsGroupMember:input_type -> users.GeneralGroupRequest
	18, // 26: users.UserService.RequestJoinGroupOrCancel:input_type -> users.GroupJoinRequest
	19, // 27: users.UserService.RespondToGroupInvite:input_type -> users.HandleGroupInviteRequest
	20, // 28: users.UserService.HandleGroupJoinRequest:input_type -> users.HandleJoinRequest
	12, // 29: users.UserService.LeaveGroup:input_type -> users.GeneralGroupRequest
	22, // 30: users.UserService.CreateGroup:input_type -> users.CreateGroupRequest
	29, // 31: users.UserService.GetBasicUserInfo:input_type -> google.protobuf.Int64Value
	30, // 32: users.UserService.GetBatchBasicUserInfo:input_type -> common.Int64Arr
	24, // 33: users.UserService.GetUserProfile:input_type -> users.GetUserProfileRequest
	25, // 34: users.UserService.SearchUsers:input_type -> users.UserSearchRequest
	26, // 35: users.UserService.UpdateUserProfile:input_type -> users.UpdateProfileRequest
	27, // 36: users.UserService.UpdateProfilePrivacy:input_type -> users.UpdateProfilePrivacyRequest
	31, // 37: users.UserService.RegisterUser:output_type -> common.User
	31, // 38: users.UserService.LoginUser:output_type -> common.User
	32, // 39: users.UserService.UpdateUserPassword:output_type -> google.protobuf.Empty
	32, // 40: users.UserService.UpdateUserEmail:output_type -> google.protobuf.Empty
	33, // 41: users.UserService.GetFollowersPaginated:output_type -> common.ListUsers
	33, // 42: users.UserService.GetFollowingPaginated:output_type -> common.ListUsers
	7,  // 43: users.UserService.FollowUser:output_type -> users.FollowUserResponse
	34, // 44: users.UserService.UnFollowUser:output_type -> google.protobuf.BoolValue
	32, // 45: users.UserService.HandleFollowRequest:output_type -> google.protobuf.Empty
	30, // 46: users.UserService.GetFollowingIds:output_type -> common.Int64Arr
	33, // 47: users.UserService.GetFollowSuggestions:output_type -> common.ListUsers
	34, // 48: users.UserService.IsFollowing:output_type -> google.protobuf.BoolValue
	34, // 49: users.UserService.AreFollowingEachOther:output_type -> google.protobuf.BoolValue
	11, // 50: users.UserService.GetAllGroupsPaginated:output_type -> users.GroupArr
	11, // 51: users.UserService.GetUserGroupsPaginated:output_type -> users.GroupArr
	10, // 52: users.UserService.GetGroupInfo:output_type -> users.Group
	15, // 53: users.UserService.GetGroupMembers:output_type -> users.GroupUserArr
	11, // 54: users.UserService.SearchGroups:output_type -> users.GroupArr
	32, // 55: users.UserService.InviteToGroup:output_type -> google.protobuf.Empty
	34, // 56: users.UserService.IsGroupMember:output_type -> google.protobuf.BoolValue
	32, // 57: users.UserService.RequestJoinGroupOrCancel:output_type -> google.protobuf.Empty
	32, // 58: users.UserService.RespondToGroupInvite:output_type -> google.protobuf.Empty
	32, // 59: users.UserService.HandleGroupJoinRequest:output_type -> google.protobuf.Empty
	32, // 60: users.UserService.LeaveGroup:output_type -> google.protobuf.Empty
	29, // 61: users.UserService.CreateGroup:output_type -> google.protobuf.Int64Value
	31, // 62: users.UserService.GetBasicUserInfo:output_type -> common.User
	33, // 63: users.UserService.GetBatchBasicUserInfo:output_type -> common.ListUsers
	0,  // 64: users.UserService.GetUserProfile:output_type -> users.UserProfileResponse
	33, // 65: users.UserService.SearchUsers:output_type -> common.ListUsers
	0,  // 66: users.UserService.UpdateUserProfile:output_type -> users.UserProfileResponse
	32, // 67: users.UserService.UpdateProfilePrivacy:output_type -> google.protobuf.Empty
	37, // [37:68] is the sub-list for method output_type
	6,  // [6:37] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
