export const getMockUsers = () => {
    return [
        {
            ID: "1",
            Username: "ychaniot",
            firstName: "Ypatios",
            lastName: "Chaniotakos",
            AboutMe: "Hello World!! I'm always up for a good conversation or a cup of coffee.",
            DateOfBirth: "1995-02-07",
            CreatedAt: "2023-01-15",
            Avatar: "/putin.jpeg",
            isFollower: false,
            publicProf: true,
            IsPending: false,
            FollowersNum: 1234,
            FollowingNum: 567,
            GroupsNum: 12,
        },
        {
            ID: "2",
            Username: "gtoaka",
            firstName: "Georgia",
            lastName: "Toaka",
            AboutMe: "Hello World!! I'm always up for a good conversation or a cup of coffee.",
            DateOfBirth: "1992-05-21",
            CreatedAt: "2023-01-15",
            Avatar: "/logo.png",
            isFollower: true,
            publicProf: true,
            IsPending: false,
            FollowersNum: 6545,
            FollowingNum: 1243,
            GroupsNum: 123,
        },
        {
            ID: "3",
            Username: "privateuser",
            firstName: "Private",
            lastName: "User",
            AboutMe: "Hello World!! I'm always up for a good conversation or a cup of coffee.",
            DateOfBirth: "1992-05-21",
            CreatedAt: "2023-01-15",
            Avatar: "/logos.png",
            isFollower: false,
            publicProf: false,
            IsPending: false,
            FollowersNum: 6545,
            FollowingNum: 1243,
            GroupsNum: 123,
        },
        {
            ID: "4",
            Username: "watermelon_musk",
            firstName: "Watermelon",
            lastName: "Musk",
            AboutMe: "Hello World!! I'm always up for a good conversation or a cup of coffee.",
            DateOfBirth: "1992-05-21",
            CreatedAt: "2023-01-15",
            Avatar: "/elon.jpeg",
            isFollower: true,
            publicProf: true,
            IsPending: false,
            FollowersNum: 6545,
            FollowingNum: 1243,
            GroupsNum: 123,
        },
        {
            ID: "5",
            Username: "trumpet",
            firstName: "Trumpet",
            lastName: "Trump",
            AboutMe: "Hello World!! I'm always up for a good conversation or a cup of coffee.",
            DateOfBirth: "1992-05-21",
            CreatedAt: "2023-01-15",
            Avatar: "/trump.jpeg",
            isFollower: true,
            publicProf: true,
            IsPending: false,
            FollowersNum: 6545,
            FollowingNum: 1243,
            GroupsNum: 123,
        },
        {
            ID: "6",
            Username: "kimpossible",
            firstName: "Kim",
            lastName: "Possible",
            AboutMe: null,
            DateOfBirth: "1992-05-21",
            CreatedAt: "2023-01-15",
            Avatar: "/kim.jpeg",
            isFollower: false,
            publicProf: false,
            IsPending: false,
            FollowersNum: 6545,
            FollowingNum: 1243,
            GroupsNum: 123,
        },
        {
            ID: "7",
            Username: "xi_aomi",
            firstName: "Xi",
            lastName: "Aomi",
            AboutMe: "Hello World!! I'm always up for a good conversation or a cup of coffee.",
            DateOfBirth: "1992-05-21",
            CreatedAt: "2023-01-15",
            Avatar: "/xi.jpeg",
            isFollower: false,
            publicProf: true,
            IsPending: false,
            FollowersNum: 6545,
            FollowingNum: 1243,
            GroupsNum: 123,
        }
    ]
}

export const getUserByID = (id) => {
    return getMockUsers().find(user => user.ID === id);
}
