package application

import (
	"encoding/json"

	"social-network/services/notifications/internal/db/sqlc"

	"github.com/jackc/pgx/v5/pgtype"
)

// DBQuerier defines the interface for database operations
// This matches the interface generated by sqlc
type DBQuerier interface {
	sqlc.Querier
}

// ConvertDBNotification converts a sqlc database notification to application notification
func ConvertDBNotification(dbNotif interface{}) Notification {
	// The interface can be different row types depending on which query was used
	var (
		id             int64
		userID         int64
		notifType      string
		sourceService  string
		sourceEntityID pgtype.Int8
		seen           pgtype.Bool
		needsAction    pgtype.Bool
		acted          pgtype.Bool
		payload        []byte
		createdAt      pgtype.Timestamptz
		expiresAt      pgtype.Timestamptz
	)

	switch n := dbNotif.(type) {
	case sqlc.GetNotificationsByUserIdAllRow:
		id = n.ID
		userID = n.UserID
		notifType = n.NotifType
		sourceService = n.SourceService
		sourceEntityID = n.SourceEntityID
		seen = n.Seen
		needsAction = n.NeedsAction
		acted = n.Acted
		payload = n.Payload
		createdAt = n.CreatedAt
		expiresAt = n.ExpiresAt
	case sqlc.GetNotificationsByUserIdFilteredByStatusRow:
		id = n.ID
		userID = n.UserID
		notifType = n.NotifType
		sourceService = n.SourceService
		sourceEntityID = n.SourceEntityID
		seen = n.Seen
		needsAction = n.NeedsAction
		acted = n.Acted
		payload = n.Payload
		createdAt = n.CreatedAt
		expiresAt = n.ExpiresAt
	}

	payloadMap := make(map[string]string)
	if len(payload) > 0 {
		// Try to unmarshal the JSON payload
		if err := json.Unmarshal(payload, &payloadMap); err == nil {
			// If unmarshaling succeeds, use the map. If it fails, payloadMap will remain empty.
		}
	}

	var entityID int64
	if sourceEntityID.Valid {
		entityID = sourceEntityID.Int64
	}

	return Notification{
		ID:             id,
		UserID:         userID,
		Type:           NotificationType(notifType),
		SourceService:  SourceService(sourceService),
		SourceEntityID: entityID,
		Seen:           seen.Bool,
		NeedsAction:    needsAction.Bool,
		Acted:          acted.Bool,
		Payload:        payloadMap,
		CreatedAt:      createdAt.Time,
		ExpiresAt:      expiresAt.Time,
	}
}

// ConvertCreateNotificationParams converts an application request to sqlc parameters
func ConvertCreateNotificationParams(req *CreateNotificationRequest) (sqlc.CreateNotificationParams, error) {
	payloadBytes, err := json.Marshal(req.Payload)
	if err != nil {
		return sqlc.CreateNotificationParams{}, err
	}

	var sourceEntityID pgtype.Int8
	if req.SourceEntityID != 0 {
		sourceEntityID = pgtype.Int8{Int64: req.SourceEntityID, Valid: true}
	} else {
		sourceEntityID = pgtype.Int8{Valid: false}
	}

	return sqlc.CreateNotificationParams{
		Column1: pgtype.Int8{Int64: req.UserID, Valid: true},
		Column2: pgtype.Text{String: string(req.Type), Valid: true},
		Column3: pgtype.Text{String: string(req.SourceService), Valid: true},
		Column4: sourceEntityID,
		Column5: payloadBytes,
	}, nil
}