// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: followers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFollowRequest = `-- name: AcceptFollowRequest :exec
WITH updated AS (
    UPDATE follow_requests
    SET status = 'accepted', updated_at = NOW()
    WHERE requester_id = get_internal_user_id($1)
      AND target_id    = get_internal_user_id($2)
      AND deleted_at IS NULL
    RETURNING requester_id, target_id
)
INSERT INTO follows (follower_id, following_id)
SELECT requester_id, target_id
FROM updated
ON CONFLICT DO NOTHING
`

type AcceptFollowRequestParams struct {
	Pub   pgtype.UUID
	Pub_2 pgtype.UUID
}

func (q *Queries) AcceptFollowRequest(ctx context.Context, arg AcceptFollowRequestParams) error {
	_, err := q.db.Exec(ctx, acceptFollowRequest, arg.Pub, arg.Pub_2)
	return err
}

const followUser = `-- name: FollowUser :one
SELECT follow_user(get_internal_user_id($1), get_internal_user_id($2))
`

type FollowUserParams struct {
	Pub   pgtype.UUID
	Pub_2 pgtype.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (string, error) {
	row := q.db.QueryRow(ctx, followUser, arg.Pub, arg.Pub_2)
	var follow_user string
	err := row.Scan(&follow_user)
	return follow_user, err
}

const getFollowerCount = `-- name: GetFollowerCount :one
SELECT COUNT(*) AS follower_count
FROM follows
WHERE following_id = get_internal_user_id($1)
`

func (q *Queries) GetFollowerCount(ctx context.Context, pub pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowerCount, pub)
	var follower_count int64
	err := row.Scan(&follower_count)
	return follower_count, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.public_id, u.username, u.avatar,u.profile_public, f.created_at AS followed_at
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.following_id = get_internal_user_id($1)
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersParams struct {
	Pub    pgtype.UUID
	Limit  int32
	Offset int32
}

type GetFollowersRow struct {
	PublicID      pgtype.UUID
	Username      string
	Avatar        string
	ProfilePublic bool
	FollowedAt    pgtype.Timestamptz
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]GetFollowersRow, error) {
	rows, err := q.db.Query(ctx, getFollowers, arg.Pub, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowersRow{}
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Username,
			&i.Avatar,
			&i.ProfilePublic,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.public_id, u.username,u.avatar,u.profile_public, f.created_at AS followed_at
FROM follows f
JOIN users u ON u.id = f.following_id
WHERE f.follower_id = get_internal_user_id($1)
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingParams struct {
	Pub    pgtype.UUID
	Limit  int32
	Offset int32
}

type GetFollowingRow struct {
	PublicID      pgtype.UUID
	Username      string
	Avatar        string
	ProfilePublic bool
	FollowedAt    pgtype.Timestamptz
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]GetFollowingRow, error) {
	rows, err := q.db.Query(ctx, getFollowing, arg.Pub, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingRow{}
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Username,
			&i.Avatar,
			&i.ProfilePublic,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*) AS following_count
FROM follows
WHERE follower_id = get_internal_user_id($1)
`

func (q *Queries) GetFollowingCount(ctx context.Context, pub pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCount, pub)
	var following_count int64
	err := row.Scan(&following_count)
	return following_count, err
}

const getMutualFollowers = `-- name: GetMutualFollowers :many
SELECT u.public_id, u.username
FROM follows f1
JOIN follows f2 ON f1.follower_id = f2.follower_id
JOIN users u ON u.id = f1.follower_id
WHERE f1.following_id = get_internal_user_id($1)
  AND f2.following_id = get_internal_user_id($2)
`

type GetMutualFollowersParams struct {
	Pub   pgtype.UUID
	Pub_2 pgtype.UUID
}

type GetMutualFollowersRow struct {
	PublicID pgtype.UUID
	Username string
}

func (q *Queries) GetMutualFollowers(ctx context.Context, arg GetMutualFollowersParams) ([]GetMutualFollowersRow, error) {
	rows, err := q.db.Query(ctx, getMutualFollowers, arg.Pub, arg.Pub_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMutualFollowersRow{}
	for rows.Next() {
		var i GetMutualFollowersRow
		if err := rows.Scan(&i.PublicID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_id = get_internal_user_id($1) AND following_id = get_internal_user_id($2)
)
`

type IsFollowingParams struct {
	Pub   pgtype.UUID
	Pub_2 pgtype.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.Pub, arg.Pub_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isFollowingEither = `-- name: IsFollowingEither :one
SELECT EXISTS (
    SELECT 1
    FROM follows
    WHERE (follower_id = get_internal_user_id($1) AND following_id = get_internal_user_id($2))
       OR (follower_id = get_internal_user_id($2) AND following_id = get_internal_user_id($1))
) AS is_following_either
`

type IsFollowingEitherParams struct {
	Pub   pgtype.UUID
	Pub_2 pgtype.UUID
}

func (q *Queries) IsFollowingEither(ctx context.Context, arg IsFollowingEitherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingEither, arg.Pub, arg.Pub_2)
	var is_following_either bool
	err := row.Scan(&is_following_either)
	return is_following_either, err
}

const rejectFollowRequest = `-- name: RejectFollowRequest :exec
UPDATE follow_requests
SET status = 'rejected', updated_at = NOW()
WHERE requester_id = get_internal_user_id($1) AND target_id = get_internal_user_id($2)
`

type RejectFollowRequestParams struct {
	Pub   pgtype.UUID
	Pub_2 pgtype.UUID
}

func (q *Queries) RejectFollowRequest(ctx context.Context, arg RejectFollowRequestParams) error {
	_, err := q.db.Exec(ctx, rejectFollowRequest, arg.Pub, arg.Pub_2)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec


DELETE FROM follows
WHERE follower_id = get_internal_user_id($1) AND following_id = get_internal_user_id($2)
`

type UnfollowUserParams struct {
	Pub   pgtype.UUID
	Pub_2 pgtype.UUID
}

// 1: follower_id
// 2: following_id
// returns followed or requested depending on target's privacy settings
func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.Pub, arg.Pub_2)
	return err
}
