// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"database/sql"
)

const acceptGroupInvite = `-- name: AcceptGroupInvite :exec
UPDATE group_invites
SET status = 'accepted'
WHERE group_id = $1
  AND receiver_id = $2
`

type AcceptGroupInviteParams struct {
	GroupID    int64 `json:"group_id"`
	ReceiverID int64 `json:"receiver_id"`
}

func (q *Queries) AcceptGroupInvite(ctx context.Context, arg AcceptGroupInviteParams) error {
	_, err := q.db.ExecContext(ctx, acceptGroupInvite, arg.GroupID, arg.ReceiverID)
	return err
}

const acceptGroupJoinRequest = `-- name: AcceptGroupJoinRequest :exec
UPDATE group_join_requests
SET status = 'accepted'
WHERE group_id = $1
  AND user_id = $2
`

type AcceptGroupJoinRequestParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AcceptGroupJoinRequest(ctx context.Context, arg AcceptGroupJoinRequestParams) error {
	_, err := q.db.ExecContext(ctx, acceptGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const addGroupOwnerAsMember = `-- name: AddGroupOwnerAsMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, 'owner')
`

type AddGroupOwnerAsMemberParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AddGroupOwnerAsMember(ctx context.Context, arg AddGroupOwnerAsMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupOwnerAsMember, arg.GroupID, arg.UserID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserToGroupParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.GroupID, arg.UserID)
	return err
}

const cancelGroupInvite = `-- name: CancelGroupInvite :exec
DELETE FROM group_invites
WHERE group_id = $1
  AND receiver_id = $2
`

type CancelGroupInviteParams struct {
	GroupID    int64 `json:"group_id"`
	ReceiverID int64 `json:"receiver_id"`
}

func (q *Queries) CancelGroupInvite(ctx context.Context, arg CancelGroupInviteParams) error {
	_, err := q.db.ExecContext(ctx, cancelGroupInvite, arg.GroupID, arg.ReceiverID)
	return err
}

const cancelGroupJoinRequest = `-- name: CancelGroupJoinRequest :exec
DELETE FROM group_join_requests
WHERE group_id = $1
  AND user_id = $2
`

type CancelGroupJoinRequestParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) CancelGroupJoinRequest(ctx context.Context, arg CancelGroupJoinRequestParams) error {
	_, err := q.db.ExecContext(ctx, cancelGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_owner, group_title, group_description)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateGroupParams struct {
	GroupOwner       int64  `json:"group_owner"`
	GroupTitle       string `json:"group_title"`
	GroupDescription string `json:"group_description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.GroupOwner, arg.GroupTitle, arg.GroupDescription)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const declineGroupInvite = `-- name: DeclineGroupInvite :exec
UPDATE group_invites
SET status = 'declined'
WHERE group_id = $1
  AND receiver_id = $2
`

type DeclineGroupInviteParams struct {
	GroupID    int64 `json:"group_id"`
	ReceiverID int64 `json:"receiver_id"`
}

func (q *Queries) DeclineGroupInvite(ctx context.Context, arg DeclineGroupInviteParams) error {
	_, err := q.db.ExecContext(ctx, declineGroupInvite, arg.GroupID, arg.ReceiverID)
	return err
}

const leaveGroup = `-- name: LeaveGroup :exec
UPDATE group_members
SET deleted_at = CURRENT_TIMESTAMP
WHERE group_id = $1
  AND user_id = $2
  AND role <> 'owner'
`

type LeaveGroupParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) LeaveGroup(ctx context.Context, arg LeaveGroupParams) error {
	_, err := q.db.ExecContext(ctx, leaveGroup, arg.GroupID, arg.UserID)
	return err
}

const rejectGroupJoinRequest = `-- name: RejectGroupJoinRequest :exec
UPDATE group_join_requests
SET status = 'rejected'
WHERE group_id = $1
  AND user_id = $2
`

type RejectGroupJoinRequestParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) RejectGroupJoinRequest(ctx context.Context, arg RejectGroupJoinRequestParams) error {
	_, err := q.db.ExecContext(ctx, rejectGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const sendGroupInvite = `-- name: SendGroupInvite :exec
INSERT INTO group_invites (group_id, sender_id, receiver_id, status)
VALUES ($1, $2, $3, 'pending') 
ON CONFLICT (group_id, receiver_id)
DO UPDATE SET status = 'pending'
`

type SendGroupInviteParams struct {
	GroupID    int64         `json:"group_id"`
	SenderID   sql.NullInt64 `json:"sender_id"`
	ReceiverID int64         `json:"receiver_id"`
}

func (q *Queries) SendGroupInvite(ctx context.Context, arg SendGroupInviteParams) error {
	_, err := q.db.ExecContext(ctx, sendGroupInvite, arg.GroupID, arg.SenderID, arg.ReceiverID)
	return err
}

const sendGroupJoinRequest = `-- name: SendGroupJoinRequest :exec
INSERT INTO group_join_requests (group_id, user_id, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (group_id, user_id)
DO UPDATE SET status = 'pending'
`

type SendGroupJoinRequestParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) SendGroupJoinRequest(ctx context.Context, arg SendGroupJoinRequestParams) error {
	_, err := q.db.ExecContext(ctx, sendGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE groups
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteGroup, id)
	return err
}
