// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptGroupInvite = `-- name: AcceptGroupInvite :exec
UPDATE group_invites
SET status = 'accepted'
WHERE group_id = $1
  AND receiver_id = $2
`

type AcceptGroupInviteParams struct {
	GroupID    int64
	ReceiverID int64
}

func (q *Queries) AcceptGroupInvite(ctx context.Context, arg AcceptGroupInviteParams) error {
	_, err := q.db.Exec(ctx, acceptGroupInvite, arg.GroupID, arg.ReceiverID)
	return err
}

const acceptGroupJoinRequest = `-- name: AcceptGroupJoinRequest :exec
UPDATE group_join_requests
SET status = 'accepted'
WHERE group_id = $1
  AND user_id = $2
`

type AcceptGroupJoinRequestParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) AcceptGroupJoinRequest(ctx context.Context, arg AcceptGroupJoinRequestParams) error {
	_, err := q.db.Exec(ctx, acceptGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const addGroupOwnerAsMember = `-- name: AddGroupOwnerAsMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, 'owner')
`

type AddGroupOwnerAsMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) AddGroupOwnerAsMember(ctx context.Context, arg AddGroupOwnerAsMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupOwnerAsMember, arg.GroupID, arg.UserID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserToGroupParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addUserToGroup, arg.GroupID, arg.UserID)
	return err
}

const cancelGroupInvite = `-- name: CancelGroupInvite :exec
DELETE FROM group_invites
WHERE group_id = $1
  AND receiver_id = $2
  AND sender_id=$3
`

type CancelGroupInviteParams struct {
	GroupID    int64
	ReceiverID int64
	SenderID   int64
}

func (q *Queries) CancelGroupInvite(ctx context.Context, arg CancelGroupInviteParams) error {
	_, err := q.db.Exec(ctx, cancelGroupInvite, arg.GroupID, arg.ReceiverID, arg.SenderID)
	return err
}

const cancelGroupJoinRequest = `-- name: CancelGroupJoinRequest :exec
DELETE FROM group_join_requests
WHERE group_id = $1
  AND user_id = $2
`

type CancelGroupJoinRequestParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) CancelGroupJoinRequest(ctx context.Context, arg CancelGroupJoinRequestParams) error {
	_, err := q.db.Exec(ctx, cancelGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_owner, group_title, group_description)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateGroupParams struct {
	GroupOwner       int64
	GroupTitle       string
	GroupDescription string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.GroupOwner, arg.GroupTitle, arg.GroupDescription)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const declineGroupInvite = `-- name: DeclineGroupInvite :exec
UPDATE group_invites
SET status = 'declined'
WHERE group_id = $1
  AND receiver_id = $2
`

type DeclineGroupInviteParams struct {
	GroupID    int64
	ReceiverID int64
}

func (q *Queries) DeclineGroupInvite(ctx context.Context, arg DeclineGroupInviteParams) error {
	_, err := q.db.Exec(ctx, declineGroupInvite, arg.GroupID, arg.ReceiverID)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT 
  id,
  group_title,
  group_description,
  members_count
FROM groups
WHERE deleted_at IS NULL
`

type GetAllGroupsRow struct {
	ID               int64
	GroupTitle       string
	GroupDescription string
	MembersCount     int32
}

func (q *Queries) GetAllGroups(ctx context.Context) ([]GetAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllGroupsRow{}
	for rows.Next() {
		var i GetAllGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupTitle,
			&i.GroupDescription,
			&i.MembersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupInfo = `-- name: GetGroupInfo :one
SELECT
  id,
  group_owner,
  group_title,
  group_description,
  members_count
FROM groups
WHERE id=$1
  AND deleted_at IS NULL
`

type GetGroupInfoRow struct {
	ID               int64
	GroupOwner       int64
	GroupTitle       string
	GroupDescription string
	MembersCount     int32
}

func (q *Queries) GetGroupInfo(ctx context.Context, id int64) (GetGroupInfoRow, error) {
	row := q.db.QueryRow(ctx, getGroupInfo, id)
	var i GetGroupInfoRow
	err := row.Scan(
		&i.ID,
		&i.GroupOwner,
		&i.GroupTitle,
		&i.GroupDescription,
		&i.MembersCount,
	)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT
    gm.user_id,
    u.username,
    u.avatar,
    u.profile_public,
    gm.role,
    gm.joined_at
FROM group_members gm
JOIN users u
    ON gm.user_id = u.id
WHERE gm.group_id = $1
  AND gm.deleted_at IS NULL
`

type GetGroupMembersRow struct {
	UserID        int64
	Username      string
	Avatar        string
	ProfilePublic bool
	Role          NullGroupRole
	JoinedAt      pgtype.Timestamptz
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID int64) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.ProfilePublic,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroupRole = `-- name: GetUserGroupRole :one
SELECT role
FROM group_members
WHERE group_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetUserGroupRoleParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) GetUserGroupRole(ctx context.Context, arg GetUserGroupRoleParams) (NullGroupRole, error) {
	row := q.db.QueryRow(ctx, getUserGroupRole, arg.GroupID, arg.UserID)
	var role NullGroupRole
	err := row.Scan(&role)
	return role, err
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT DISTINCT
    g.id AS group_id,
    g.group_title,
    g.group_description,
    g.members_count,
    CASE 
        WHEN g.group_owner = $1 THEN 'owner'
        ELSE 'member'
    END AS role
FROM groups g
LEFT JOIN group_members gm
    ON gm.group_id = g.id
    AND gm.user_id = $1
    AND gm.deleted_at IS NULL
WHERE g.deleted_at IS NULL
  AND (g.group_owner = $1 OR gm.user_id = $1)
`

type GetUserGroupsRow struct {
	GroupID          int64
	GroupTitle       string
	GroupDescription string
	MembersCount     int32
	Role             string
}

func (q *Queries) GetUserGroups(ctx context.Context, groupOwner int64) ([]GetUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, getUserGroups, groupOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserGroupsRow{}
	for rows.Next() {
		var i GetUserGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupTitle,
			&i.GroupDescription,
			&i.MembersCount,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserGroupMember = `-- name: IsUserGroupMember :one
SELECT EXISTS (
    SELECT 1
    FROM group_members
    WHERE group_id = $1
      AND user_id = $2
      AND deleted_at IS NULL
) AS is_member
`

type IsUserGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) IsUserGroupMember(ctx context.Context, arg IsUserGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const isUserGroupOwner = `-- name: IsUserGroupOwner :one
SELECT (group_owner = $2) AS is_owner
FROM groups
WHERE id = $1
  AND deleted_at IS NULL
`

type IsUserGroupOwnerParams struct {
	ID         int64
	GroupOwner int64
}

func (q *Queries) IsUserGroupOwner(ctx context.Context, arg IsUserGroupOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserGroupOwner, arg.ID, arg.GroupOwner)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const leaveGroup = `-- name: LeaveGroup :exec
UPDATE group_members
SET deleted_at = CURRENT_TIMESTAMP
WHERE group_id = $1
  AND user_id = $2
  AND role <> 'owner'
`

type LeaveGroupParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) LeaveGroup(ctx context.Context, arg LeaveGroupParams) error {
	_, err := q.db.Exec(ctx, leaveGroup, arg.GroupID, arg.UserID)
	return err
}

const rejectGroupJoinRequest = `-- name: RejectGroupJoinRequest :exec
UPDATE group_join_requests
SET status = 'rejected'
WHERE group_id = $1
  AND user_id = $2
`

type RejectGroupJoinRequestParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) RejectGroupJoinRequest(ctx context.Context, arg RejectGroupJoinRequestParams) error {
	_, err := q.db.Exec(ctx, rejectGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const searchGroupsFuzzy = `-- name: SearchGroupsFuzzy :many
SELECT
    id,
    group_title,
    group_description,
    members_count
FROM groups
WHERE deleted_at IS NULL
  AND (similarity(group_title, $1) > 0.3
       OR similarity(group_description, $1) > 0.3)
ORDER BY GREATEST(similarity(group_title, $1), similarity(group_description, $1)) DESC
`

type SearchGroupsFuzzyRow struct {
	ID               int64
	GroupTitle       string
	GroupDescription string
	MembersCount     int32
}

func (q *Queries) SearchGroupsFuzzy(ctx context.Context, similarity string) ([]SearchGroupsFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchGroupsFuzzy, similarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGroupsFuzzyRow{}
	for rows.Next() {
		var i SearchGroupsFuzzyRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupTitle,
			&i.GroupDescription,
			&i.MembersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendGroupInvite = `-- name: SendGroupInvite :exec
INSERT INTO group_invites (group_id, sender_id, receiver_id, status)
VALUES ($1, $2, $3, 'pending') 
ON CONFLICT (group_id, receiver_id)
DO UPDATE SET status = 'pending'
`

type SendGroupInviteParams struct {
	GroupID    int64
	SenderID   int64
	ReceiverID int64
}

func (q *Queries) SendGroupInvite(ctx context.Context, arg SendGroupInviteParams) error {
	_, err := q.db.Exec(ctx, sendGroupInvite, arg.GroupID, arg.SenderID, arg.ReceiverID)
	return err
}

const sendGroupJoinRequest = `-- name: SendGroupJoinRequest :exec
INSERT INTO group_join_requests (group_id, user_id, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (group_id, user_id)
DO UPDATE SET status = 'pending'
`

type SendGroupJoinRequestParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) SendGroupJoinRequest(ctx context.Context, arg SendGroupJoinRequestParams) error {
	_, err := q.db.Exec(ctx, sendGroupJoinRequest, arg.GroupID, arg.UserID)
	return err
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE groups
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteGroup, id)
	return err
}

const transferOwnership = `-- name: TransferOwnership :exec


WITH demote AS (
    UPDATE group_members AS gm_old
    SET role = 'member'
    WHERE gm_old.group_id = $1
      AND gm_old.user_id = $2
      AND gm_old.role = 'owner'
),
promote AS (
    UPDATE group_members AS gm_new
    SET role = 'owner'
    WHERE gm_new.group_id = $1
      AND gm_new.user_id = $3
      AND gm_new.role = 'member'
)
SELECT 1
`

type TransferOwnershipParams struct {
	GroupID  int64
	UserID   int64
	UserID_2 int64
}

// owners cannot leave the group (transfer ownership logic? TODO)
func (q *Queries) TransferOwnership(ctx context.Context, arg TransferOwnershipParams) error {
	_, err := q.db.Exec(ctx, transferOwnership, arg.GroupID, arg.UserID, arg.UserID_2)
	return err
}
