// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserBasic = `-- name: GetUserBasic :one
SELECT
    public_id,
    username,
    avatar
FROM users
WHERE id = get_internal_user_id($1)
`

type GetUserBasicRow struct {
	PublicID pgtype.UUID
	Username string
	Avatar   string
}

func (q *Queries) GetUserBasic(ctx context.Context, pub pgtype.UUID) (GetUserBasicRow, error) {
	row := q.db.QueryRow(ctx, getUserBasic, pub)
	var i GetUserBasicRow
	err := row.Scan(&i.PublicID, &i.Username, &i.Avatar)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
    public_id,
    username,
    first_name,
    last_name,
    date_of_birth,
    avatar,
    about_me,
    profile_public,
    created_at
FROM users
WHERE id = get_internal_user_id($1)
  AND deleted_at IS NULL
`

type GetUserProfileRow struct {
	PublicID      pgtype.UUID
	Username      string
	FirstName     string
	LastName      string
	DateOfBirth   pgtype.Date
	Avatar        string
	AboutMe       string
	ProfilePublic bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUserProfile(ctx context.Context, pub pgtype.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, pub)
	var i GetUserProfileRow
	err := row.Scan(
		&i.PublicID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Avatar,
		&i.AboutMe,
		&i.ProfilePublic,
		&i.CreatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT
    public_id,
    username,
    avatar,
    profile_public
FROM users
WHERE deleted_at IS NULL
  AND (
        username % $1 OR
        first_name % $1 OR
        last_name % $1
      )
ORDER BY similarity(username, $1) DESC,
         similarity(first_name, $1) DESC,
         similarity(last_name, $1) DESC
LIMIT $2
`

type SearchUsersParams struct {
	Username string
	Limit    int32
}

type SearchUsersRow struct {
	PublicID      pgtype.UUID
	Username      string
	Avatar        string
	ProfilePublic bool
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Username, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Username,
			&i.Avatar,
			&i.ProfilePublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfilePrivacy = `-- name: UpdateProfilePrivacy :exec
UPDATE users
SET profile_public=$2
WHERE id=get_internal_user_id($1)
`

type UpdateProfilePrivacyParams struct {
	Pub           pgtype.UUID
	ProfilePublic bool
}

func (q *Queries) UpdateProfilePrivacy(ctx context.Context, arg UpdateProfilePrivacyParams) error {
	_, err := q.db.Exec(ctx, updateProfilePrivacy, arg.Pub, arg.ProfilePublic)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE auth_user
SET
    email = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = get_internal_user_id($1)
`

type UpdateUserEmailParams struct {
	Pub   pgtype.UUID
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Pub, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth_user
SET
    password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = get_internal_user_id($1)
`

type UpdateUserPasswordParams struct {
	Pub          pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Pub, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    username      = $2,
    first_name    = $3,
    last_name     = $4,
    date_of_birth = $5,
    avatar        = $6,
    about_me      = $7,
    updated_at    = CURRENT_TIMESTAMP
WHERE id = get_internal_user_id($1) AND deleted_at IS NULL
RETURNING id, public_id, username, first_name, last_name, date_of_birth, avatar, about_me, profile_public, current_status, ban_ends_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	Pub         pgtype.UUID
	Username    string
	FirstName   string
	LastName    string
	DateOfBirth pgtype.Date
	Avatar      string
	AboutMe     string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Pub,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Avatar,
		arg.AboutMe,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Avatar,
		&i.AboutMe,
		&i.ProfilePublic,
		&i.CurrentStatus,
		&i.BanEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
