// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserBasic = `-- name: GetUserBasic :one
SELECT
    username,
    avatar,
    profile_public
FROM users
WHERE id = $1
`

type GetUserBasicRow struct {
	Username      string
	Avatar        *string
	ProfilePublic bool
}

func (q *Queries) GetUserBasic(ctx context.Context, id int64) (GetUserBasicRow, error) {
	row := q.db.QueryRow(ctx, getUserBasic, id)
	var i GetUserBasicRow
	err := row.Scan(&i.Username, &i.Avatar, &i.ProfilePublic)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
    id,
    username,
    first_name,
    last_name,
    date_of_birth
    avatar,
    about_me,
    profile_public
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserProfileRow struct {
	ID            int64
	Username      string
	FirstName     string
	LastName      string
	Avatar        pgtype.Date
	AboutMe       *string
	ProfilePublic bool
}

func (q *Queries) GetUserProfile(ctx context.Context, id int64) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.AboutMe,
		&i.ProfilePublic,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT
    id,
    username,
    avatar,
    profile_public
FROM users
WHERE deleted_at IS NULL
  AND (
        username % $1 OR
        first_name % $1 OR
        last_name % $1
      )
ORDER BY similarity(username, $1) DESC,
         similarity(first_name, $1) DESC,
         similarity(last_name, $1) DESC
LIMIT $2
`

type SearchUsersParams struct {
	Username string
	Limit    int32
}

type SearchUsersRow struct {
	ID            int64
	Username      string
	Avatar        *string
	ProfilePublic bool
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Username, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Avatar,
			&i.ProfilePublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE auth_user
SET
    email = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateUserEmailParams struct {
	UserID int64
	Email  string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.UserID, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth_user
SET
    password_hash = $2,
    salt = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateUserPasswordParams struct {
	UserID       int64
	PasswordHash string
	Salt         string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.UserID, arg.PasswordHash, arg.Salt)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    first_name    = COALESCE($2, first_name),
    last_name     = COALESCE($3, last_name),
    date_of_birth = COALESCE($4, date_of_birth),
    avatar        = COALESCE($5, avatar),
    about_me      = COALESCE($6, about_me),
    updated_at    = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, username, first_name, last_name, date_of_birth, avatar, about_me, profile_public, current_status, ban_ends_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID          int64
	FirstName   string
	LastName    string
	DateOfBirth pgtype.Date
	Avatar      *string
	AboutMe     *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Avatar,
		arg.AboutMe,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Avatar,
		&i.AboutMe,
		&i.ProfilePublic,
		&i.CurrentStatus,
		&i.BanEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
