// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_CreatePrivateConversation_FullMethodName        = "/chat.ChatService/CreatePrivateConversation"
	ChatService_CreateGroupConversation_FullMethodName          = "/chat.ChatService/CreateGroupConversation"
	ChatService_AddMembersToGroupConversation_FullMethodName    = "/chat.ChatService/AddMembersToGroupConversation"
	ChatService_DeleteConversationByExactMembers_FullMethodName = "/chat.ChatService/DeleteConversationByExactMembers"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Responsible for chat service.
// Current behavior: handlers return INTERNAL for any application error; no request validation codes are emitted.
// Desired (not yet implemented): INVALID_ARGUMENT for bad member lists, ALREADY_EXISTS for duplicate DMs, NOT_FOUND for missing conversations/groups, PERMISSION_DENIED for unauthorized changes.
type ChatServiceClient interface {
	// Creates a direct message (DM) conversation between two users.
	// A conversation is created only if no existing DM between the same users exists.
	// Returns NULL if a duplicate DM exists (sqlc will error if RETURNING finds no rows).
	// Returns Error: INTERNAL on failure. Desired: INVALID_ARGUMENT for same user ids; ALREADY_EXISTS if DM already exists.
	CreatePrivateConversation(ctx context.Context, in *CreatePrivateConvParams, opts ...grpc.CallOption) (*ConvId, error)
	// Creates a group conversation associated with the given group_id.
	// This initializes the conversation but does not require adding all members yet.
	// Returns Error: INTERNAL on failure. Desired: NOT_FOUND if group missing; PERMISSION_DENIED if caller lacks rights.
	CreateGroupConversation(ctx context.Context, in *CreateGroupConvParams, opts ...grpc.CallOption) (*ConvId, error)
	// Adds users to an existing group conversation identified by group_id.
	// New members are added; existing members are ignored.
	// Returns Error: INTERNAL on failure. Desired: NOT_FOUND if conversation missing; PERMISSION_DENIED if caller cannot modify membership.
	AddMembersToGroupConversation(ctx context.Context, in *AddMembersToGroupConversationParams, opts ...grpc.CallOption) (*ConvId, error)
	// Deletes a conversation only if the set of members exactly matches the provided list.
	// Returns "conversation not found" if:
	//   - the conversation does not exist, or
	//   - the members differ (extra or missing members).
	//
	// Returns Error: INTERNAL on failure. Desired: INVALID_ARGUMENT for empty member list; NOT_FOUND when no match; PERMISSION_DENIED if caller cannot delete it.
	DeleteConversationByExactMembers(ctx context.Context, in *UserIds, opts ...grpc.CallOption) (*Conversation, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CreatePrivateConversation(ctx context.Context, in *CreatePrivateConvParams, opts ...grpc.CallOption) (*ConvId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvId)
	err := c.cc.Invoke(ctx, ChatService_CreatePrivateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateGroupConversation(ctx context.Context, in *CreateGroupConvParams, opts ...grpc.CallOption) (*ConvId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvId)
	err := c.cc.Invoke(ctx, ChatService_CreateGroupConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AddMembersToGroupConversation(ctx context.Context, in *AddMembersToGroupConversationParams, opts ...grpc.CallOption) (*ConvId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvId)
	err := c.cc.Invoke(ctx, ChatService_AddMembersToGroupConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteConversationByExactMembers(ctx context.Context, in *UserIds, opts ...grpc.CallOption) (*Conversation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conversation)
	err := c.cc.Invoke(ctx, ChatService_DeleteConversationByExactMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// Responsible for chat service.
// Current behavior: handlers return INTERNAL for any application error; no request validation codes are emitted.
// Desired (not yet implemented): INVALID_ARGUMENT for bad member lists, ALREADY_EXISTS for duplicate DMs, NOT_FOUND for missing conversations/groups, PERMISSION_DENIED for unauthorized changes.
type ChatServiceServer interface {
	// Creates a direct message (DM) conversation between two users.
	// A conversation is created only if no existing DM between the same users exists.
	// Returns NULL if a duplicate DM exists (sqlc will error if RETURNING finds no rows).
	// Returns Error: INTERNAL on failure. Desired: INVALID_ARGUMENT for same user ids; ALREADY_EXISTS if DM already exists.
	CreatePrivateConversation(context.Context, *CreatePrivateConvParams) (*ConvId, error)
	// Creates a group conversation associated with the given group_id.
	// This initializes the conversation but does not require adding all members yet.
	// Returns Error: INTERNAL on failure. Desired: NOT_FOUND if group missing; PERMISSION_DENIED if caller lacks rights.
	CreateGroupConversation(context.Context, *CreateGroupConvParams) (*ConvId, error)
	// Adds users to an existing group conversation identified by group_id.
	// New members are added; existing members are ignored.
	// Returns Error: INTERNAL on failure. Desired: NOT_FOUND if conversation missing; PERMISSION_DENIED if caller cannot modify membership.
	AddMembersToGroupConversation(context.Context, *AddMembersToGroupConversationParams) (*ConvId, error)
	// Deletes a conversation only if the set of members exactly matches the provided list.
	// Returns "conversation not found" if:
	//   - the conversation does not exist, or
	//   - the members differ (extra or missing members).
	//
	// Returns Error: INTERNAL on failure. Desired: INVALID_ARGUMENT for empty member list; NOT_FOUND when no match; PERMISSION_DENIED if caller cannot delete it.
	DeleteConversationByExactMembers(context.Context, *UserIds) (*Conversation, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) CreatePrivateConversation(context.Context, *CreatePrivateConvParams) (*ConvId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrivateConversation not implemented")
}
func (UnimplementedChatServiceServer) CreateGroupConversation(context.Context, *CreateGroupConvParams) (*ConvId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroupConversation not implemented")
}
func (UnimplementedChatServiceServer) AddMembersToGroupConversation(context.Context, *AddMembersToGroupConversationParams) (*ConvId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMembersToGroupConversation not implemented")
}
func (UnimplementedChatServiceServer) DeleteConversationByExactMembers(context.Context, *UserIds) (*Conversation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConversationByExactMembers not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CreatePrivateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrivateConvParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreatePrivateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreatePrivateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreatePrivateConversation(ctx, req.(*CreatePrivateConvParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateGroupConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupConvParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateGroupConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateGroupConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateGroupConversation(ctx, req.(*CreateGroupConvParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AddMembersToGroupConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMembersToGroupConversationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddMembersToGroupConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_AddMembersToGroupConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddMembersToGroupConversation(ctx, req.(*AddMembersToGroupConversationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteConversationByExactMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteConversationByExactMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteConversationByExactMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteConversationByExactMembers(ctx, req.(*UserIds))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrivateConversation",
			Handler:    _ChatService_CreatePrivateConversation_Handler,
		},
		{
			MethodName: "CreateGroupConversation",
			Handler:    _ChatService_CreateGroupConversation_Handler,
		},
		{
			MethodName: "AddMembersToGroupConversation",
			Handler:    _ChatService_AddMembersToGroupConversation_Handler,
		},
		{
			MethodName: "DeleteConversationByExactMembers",
			Handler:    _ChatService_DeleteConversationByExactMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
