// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getUserProfile = `-- name: GetUserProfile :one
SELECT
    id,
    username,
    first_name,
    last_name,
    date_of_birth
    avatar,
    about_me,
    profile_public
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserProfileRow struct {
	ID            int64          `json:"id"`
	Username      string         `json:"username"`
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	Avatar        time.Time      `json:"avatar"`
	AboutMe       sql.NullString `json:"about_me"`
	ProfilePublic bool           `json:"profile_public"`
}

func (q *Queries) GetUserProfile(ctx context.Context, id int64) (GetUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.AboutMe,
		&i.ProfilePublic,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE auth_user
SET
    email = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateUserEmailParams struct {
	UserID int64  `json:"user_id"`
	Email  string `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.UserID, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth_user
SET
    password_hash = $2,
    salt = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateUserPasswordParams struct {
	UserID       int64  `json:"user_id"`
	PasswordHash string `json:"password_hash"`
	Salt         string `json:"salt"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.UserID, arg.PasswordHash, arg.Salt)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    date_of_birth = COALESCE($4, date_of_birth),
    avatar = COALESCE($5, avatar),
    about_me = COALESCE($6, about_me),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, username, first_name, last_name, date_of_birth, avatar, about_me, profile_public, current_status, ban_ends_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID          int64          `json:"id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	DateOfBirth time.Time      `json:"date_of_birth"`
	Avatar      sql.NullString `json:"avatar"`
	AboutMe     sql.NullString `json:"about_me"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Avatar,
		arg.AboutMe,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Avatar,
		&i.AboutMe,
		&i.ProfilePublic,
		&i.CurrentStatus,
		&i.BanEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
