// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: followers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFollowRequest = `-- name: AcceptFollowRequest :exec
WITH updated AS (
    UPDATE follow_requests
    SET status = 'accepted', updated_at = NOW()
    WHERE requester_id = $1
      AND target_id    = $2
      AND deleted_at IS NULL
    RETURNING requester_id, target_id
)
INSERT INTO follows (follower_id, following_id)
SELECT requester_id, target_id
FROM updated
ON CONFLICT DO NOTHING
`

type AcceptFollowRequestParams struct {
	RequesterID int64
	TargetID    int64
}

func (q *Queries) AcceptFollowRequest(ctx context.Context, arg AcceptFollowRequestParams) error {
	_, err := q.db.Exec(ctx, acceptFollowRequest, arg.RequesterID, arg.TargetID)
	return err
}

const followUser = `-- name: FollowUser :one
SELECT follow_user($1, $2)
`

type FollowUserParams struct {
	PFollower int64
	PTarget   int64
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (string, error) {
	row := q.db.QueryRow(ctx, followUser, arg.PFollower, arg.PTarget)
	var follow_user string
	err := row.Scan(&follow_user)
	return follow_user, err
}

const getFollowerCount = `-- name: GetFollowerCount :one
SELECT COUNT(*) AS follower_count
FROM follows
WHERE following_id = $1
`

func (q *Queries) GetFollowerCount(ctx context.Context, followingID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowerCount, followingID)
	var follower_count int64
	err := row.Scan(&follower_count)
	return follower_count, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.username, u.avatar,u.profile_public, f.created_at AS followed_at
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersParams struct {
	FollowingID int64
	Limit       int32
	Offset      int32
}

type GetFollowersRow struct {
	ID            int64
	Username      string
	Avatar        string
	ProfilePublic bool
	FollowedAt    pgtype.Timestamptz
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]GetFollowersRow, error) {
	rows, err := q.db.Query(ctx, getFollowers, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowersRow{}
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Avatar,
			&i.ProfilePublic,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id, u.username,u.avatar,u.profile_public, f.created_at AS followed_at
FROM follows f
JOIN users u ON u.id = f.following_id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingParams struct {
	FollowerID int64
	Limit      int32
	Offset     int32
}

type GetFollowingRow struct {
	ID            int64
	Username      string
	Avatar        string
	ProfilePublic bool
	FollowedAt    pgtype.Timestamptz
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]GetFollowingRow, error) {
	rows, err := q.db.Query(ctx, getFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingRow{}
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Avatar,
			&i.ProfilePublic,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*) AS following_count
FROM follows
WHERE follower_id = $1
`

func (q *Queries) GetFollowingCount(ctx context.Context, followerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCount, followerID)
	var following_count int64
	err := row.Scan(&following_count)
	return following_count, err
}

const getMutualFollowers = `-- name: GetMutualFollowers :many
SELECT u.id, u.username
FROM follows f1
JOIN follows f2 ON f1.follower_id = f2.follower_id
JOIN users u ON u.id = f1.follower_id
WHERE f1.following_id = $1
  AND f2.following_id = $2
`

type GetMutualFollowersParams struct {
	FollowingID   int64
	FollowingID_2 int64
}

type GetMutualFollowersRow struct {
	ID       int64
	Username string
}

func (q *Queries) GetMutualFollowers(ctx context.Context, arg GetMutualFollowersParams) ([]GetMutualFollowersRow, error) {
	rows, err := q.db.Query(ctx, getMutualFollowers, arg.FollowingID, arg.FollowingID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMutualFollowersRow{}
	for rows.Next() {
		var i GetMutualFollowersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_id =$1 AND following_id = $2
)
`

type IsFollowingParams struct {
	FollowerID  int64
	FollowingID int64
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isFollowingEither = `-- name: IsFollowingEither :one
SELECT EXISTS (
    SELECT 1
    FROM follows
    WHERE (follower_id = $1 AND following_id = $2)
       OR (follower_id = $2 AND following_id = $1)
) AS is_following_either
`

type IsFollowingEitherParams struct {
	FollowerID  int64
	FollowingID int64
}

func (q *Queries) IsFollowingEither(ctx context.Context, arg IsFollowingEitherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingEither, arg.FollowerID, arg.FollowingID)
	var is_following_either bool
	err := row.Scan(&is_following_either)
	return is_following_either, err
}

const rejectFollowRequest = `-- name: RejectFollowRequest :exec
UPDATE follow_requests
SET status = 'rejected', updated_at = NOW()
WHERE requester_id = $1 AND target_id = $2
`

type RejectFollowRequestParams struct {
	RequesterID int64
	TargetID    int64
}

func (q *Queries) RejectFollowRequest(ctx context.Context, arg RejectFollowRequestParams) error {
	_, err := q.db.Exec(ctx, rejectFollowRequest, arg.RequesterID, arg.TargetID)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec


DELETE FROM follows
WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  int64
	FollowingID int64
}

// 1: follower_id
// 2: following_id
// returns followed or requested depending on target's privacy settings
func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
