// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notifications.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification types
type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED                 NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_FOLLOW_REQUEST              NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_NEW_FOLLOWER                NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_GROUP_INVITE                NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_GROUP_JOIN_REQUEST          NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_NEW_EVENT                   NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_POST_LIKE                   NotificationType = 6
	NotificationType_NOTIFICATION_TYPE_POST_COMMENT                NotificationType = 7
	NotificationType_NOTIFICATION_TYPE_MENTION                     NotificationType = 8
	NotificationType_NOTIFICATION_TYPE_NEW_MESSAGE                 NotificationType = 9
	NotificationType_NOTIFICATION_TYPE_FOLLOW_REQUEST_ACCEPTED     NotificationType = 10
	NotificationType_NOTIFICATION_TYPE_FOLLOW_REQUEST_REJECTED     NotificationType = 11
	NotificationType_NOTIFICATION_TYPE_GROUP_INVITE_ACCEPTED       NotificationType = 12
	NotificationType_NOTIFICATION_TYPE_GROUP_INVITE_REJECTED       NotificationType = 13
	NotificationType_NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_ACCEPTED NotificationType = 14
	NotificationType_NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_REJECTED NotificationType = 15
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOTIFICATION_TYPE_UNSPECIFIED",
		1:  "NOTIFICATION_TYPE_FOLLOW_REQUEST",
		2:  "NOTIFICATION_TYPE_NEW_FOLLOWER",
		3:  "NOTIFICATION_TYPE_GROUP_INVITE",
		4:  "NOTIFICATION_TYPE_GROUP_JOIN_REQUEST",
		5:  "NOTIFICATION_TYPE_NEW_EVENT",
		6:  "NOTIFICATION_TYPE_POST_LIKE",
		7:  "NOTIFICATION_TYPE_POST_COMMENT",
		8:  "NOTIFICATION_TYPE_MENTION",
		9:  "NOTIFICATION_TYPE_NEW_MESSAGE",
		10: "NOTIFICATION_TYPE_FOLLOW_REQUEST_ACCEPTED",
		11: "NOTIFICATION_TYPE_FOLLOW_REQUEST_REJECTED",
		12: "NOTIFICATION_TYPE_GROUP_INVITE_ACCEPTED",
		13: "NOTIFICATION_TYPE_GROUP_INVITE_REJECTED",
		14: "NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_ACCEPTED",
		15: "NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_REJECTED",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":                 0,
		"NOTIFICATION_TYPE_FOLLOW_REQUEST":              1,
		"NOTIFICATION_TYPE_NEW_FOLLOWER":                2,
		"NOTIFICATION_TYPE_GROUP_INVITE":                3,
		"NOTIFICATION_TYPE_GROUP_JOIN_REQUEST":          4,
		"NOTIFICATION_TYPE_NEW_EVENT":                   5,
		"NOTIFICATION_TYPE_POST_LIKE":                   6,
		"NOTIFICATION_TYPE_POST_COMMENT":                7,
		"NOTIFICATION_TYPE_MENTION":                     8,
		"NOTIFICATION_TYPE_NEW_MESSAGE":                 9,
		"NOTIFICATION_TYPE_FOLLOW_REQUEST_ACCEPTED":     10,
		"NOTIFICATION_TYPE_FOLLOW_REQUEST_REJECTED":     11,
		"NOTIFICATION_TYPE_GROUP_INVITE_ACCEPTED":       12,
		"NOTIFICATION_TYPE_GROUP_INVITE_REJECTED":       13,
		"NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_ACCEPTED": 14,
		"NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_REJECTED": 15,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notifications_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

// Notification status
type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_UNREAD      NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_READ        NotificationStatus = 2
	NotificationStatus_NOTIFICATION_STATUS_DELETED     NotificationStatus = 3
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_UNREAD",
		2: "NOTIFICATION_STATUS_READ",
		3: "NOTIFICATION_STATUS_DELETED",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_UNREAD":      1,
		"NOTIFICATION_STATUS_READ":        2,
		"NOTIFICATION_STATUS_DELETED":     3,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_enumTypes[1].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_notifications_proto_enumTypes[1]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

// Main notification message
type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // recipient user id
	Type           NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	SourceService  string                 `protobuf:"bytes,6,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`                                           // e.g. "users", "posts", "groups"
	SourceEntityId int64                  `protobuf:"varint,7,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`                                     // id of the entity that triggered the notification
	NeedsAction    bool                   `protobuf:"varint,8,opt,name=needs_action,json=needsAction,proto3" json:"needs_action,omitempty"`                                                // whether user needs to take action (e.g., accept/decline)
	Acted          bool                   `protobuf:"varint,9,opt,name=acted,proto3" json:"acted,omitempty"`                                                                               // whether user has taken action
	Count          int32                  `protobuf:"varint,10,opt,name=count,proto3" json:"count,omitempty"`                                                                              // aggregation count
	Payload        map[string]string      `protobuf:"bytes,11,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // additional data in key-value pairs
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status         NotificationStatus     `protobuf:"varint,14,opt,name=status,proto3,enum=notifications.NotificationStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *Notification) GetSourceEntityId() int64 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *Notification) GetNeedsAction() bool {
	if x != nil {
		return x.NeedsAction
	}
	return false
}

func (x *Notification) GetActed() bool {
	if x != nil {
		return x.Acted
	}
	return false
}

func (x *Notification) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Notification) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Notification) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

// Request to create a single notification
type CreateNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // recipient
	Type           NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	SourceService  string                 `protobuf:"bytes,5,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	SourceEntityId int64                  `protobuf:"varint,6,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	NeedsAction    bool                   `protobuf:"varint,7,opt,name=needs_action,json=needsAction,proto3" json:"needs_action,omitempty"`
	Payload        map[string]string      `protobuf:"bytes,8,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregate      bool                   `protobuf:"varint,9,opt,name=aggregate,proto3" json:"aggregate,omitempty"` // whether to aggregate this notification with existing ones
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNotificationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *CreateNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNotificationRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *CreateNotificationRequest) GetSourceEntityId() int64 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *CreateNotificationRequest) GetNeedsAction() bool {
	if x != nil {
		return x.NeedsAction
	}
	return false
}

func (x *CreateNotificationRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateNotificationRequest) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

// Request to create multiple notifications
type CreateNotificationsRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Notifications []*CreateNotificationRequest `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationsRequest) Reset() {
	*x = CreateNotificationsRequest{}
	mi := &file_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationsRequest) ProtoMessage() {}

func (x *CreateNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationsRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotificationsRequest) GetNotifications() []*CreateNotificationRequest {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// Response for creating multiple notifications
type CreateNotificationsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CreatedNotifications []*Notification        `protobuf:"bytes,1,rep,name=created_notifications,json=createdNotifications,proto3" json:"created_notifications,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateNotificationsResponse) Reset() {
	*x = CreateNotificationsResponse{}
	mi := &file_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationsResponse) ProtoMessage() {}

func (x *CreateNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationsResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNotificationsResponse) GetCreatedNotifications() []*Notification {
	if x != nil {
		return x.CreatedNotifications
	}
	return nil
}

// Request to get user notifications
type GetUserNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Types         []NotificationType     `protobuf:"varint,4,rep,packed,name=types,proto3,enum=notifications.NotificationType" json:"types,omitempty"` // filter by types
	UnreadOnly    bool                   `protobuf:"varint,5,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`                // if true, only return unread notifications
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNotificationsRequest) Reset() {
	*x = GetUserNotificationsRequest{}
	mi := &file_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNotificationsRequest) ProtoMessage() {}

func (x *GetUserNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetUserNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserNotificationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUserNotificationsRequest) GetTypes() []NotificationType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *GetUserNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

// Response with user notifications
type GetUserNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNotificationsResponse) Reset() {
	*x = GetUserNotificationsResponse{}
	mi := &file_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNotificationsResponse) ProtoMessage() {}

func (x *GetUserNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetUserNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetUserNotificationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetUserNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// Request to mark notification as read
type MarkNotificationAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationAsReadRequest) Reset() {
	*x = MarkNotificationAsReadRequest{}
	mi := &file_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationAsReadRequest) ProtoMessage() {}

func (x *MarkNotificationAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *MarkNotificationAsReadRequest) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *MarkNotificationAsReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Request to delete notification
type DeleteNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNotificationRequest) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *DeleteNotificationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Notification preferences
type NotificationPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   map[string]bool        `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // map of notification type to enabled status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationPreferences) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationPreferences) GetPreferences() map[string]bool {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdateNotificationPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   map[string]bool        `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationPreferencesRequest) Reset() {
	*x = UpdateNotificationPreferencesRequest{}
	mi := &file_notifications_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationPreferencesRequest) ProtoMessage() {}

func (x *UpdateNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNotificationPreferencesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateNotificationPreferencesRequest) GetPreferences() map[string]bool {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// Specific notification request messages
// Request to create a follow request notification
type CreateFollowRequestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId      int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`             // recipient
	RequesterUserId   int64                  `protobuf:"varint,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`    // user that initiated the follow request
	RequesterUsername string                 `protobuf:"bytes,3,opt,name=requester_username,json=requesterUsername,proto3" json:"requester_username,omitempty"` // username of the requester
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFollowRequestRequest) Reset() {
	*x = CreateFollowRequestRequest{}
	mi := &file_notifications_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowRequestRequest) ProtoMessage() {}

func (x *CreateFollowRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateFollowRequestRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{10}
}

func (x *CreateFollowRequestRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *CreateFollowRequestRequest) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *CreateFollowRequestRequest) GetRequesterUsername() string {
	if x != nil {
		return x.RequesterUsername
	}
	return ""
}

// Request to create a new follower notification
type CreateNewFollowerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId     int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`          // recipient
	FollowerUserId   int64                  `protobuf:"varint,2,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"`    // user that started following
	FollowerUsername string                 `protobuf:"bytes,3,opt,name=follower_username,json=followerUsername,proto3" json:"follower_username,omitempty"` // username of the follower
	Aggregate        bool                   `protobuf:"varint,4,opt,name=aggregate,proto3" json:"aggregate,omitempty"`                                      // whether to aggregate this notification with existing ones
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateNewFollowerRequest) Reset() {
	*x = CreateNewFollowerRequest{}
	mi := &file_notifications_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewFollowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewFollowerRequest) ProtoMessage() {}

func (x *CreateNewFollowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewFollowerRequest.ProtoReflect.Descriptor instead.
func (*CreateNewFollowerRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNewFollowerRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *CreateNewFollowerRequest) GetFollowerUserId() int64 {
	if x != nil {
		return x.FollowerUserId
	}
	return 0
}

func (x *CreateNewFollowerRequest) GetFollowerUsername() string {
	if x != nil {
		return x.FollowerUsername
	}
	return ""
}

func (x *CreateNewFollowerRequest) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

// Request to create a group invite notification
type CreateGroupInviteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InvitedUserId   int64                  `protobuf:"varint,1,opt,name=invited_user_id,json=invitedUserId,proto3" json:"invited_user_id,omitempty"`    // recipient
	InviterUserId   int64                  `protobuf:"varint,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`    // user that sent the invite
	GroupId         int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                        // id of the group
	GroupName       string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                   // name of the group
	InviterUsername string                 `protobuf:"bytes,5,opt,name=inviter_username,json=inviterUsername,proto3" json:"inviter_username,omitempty"` // username of the inviter
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupInviteRequest) Reset() {
	*x = CreateGroupInviteRequest{}
	mi := &file_notifications_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupInviteRequest) ProtoMessage() {}

func (x *CreateGroupInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupInviteRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGroupInviteRequest) GetInvitedUserId() int64 {
	if x != nil {
		return x.InvitedUserId
	}
	return 0
}

func (x *CreateGroupInviteRequest) GetInviterUserId() int64 {
	if x != nil {
		return x.InviterUserId
	}
	return 0
}

func (x *CreateGroupInviteRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupInviteRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGroupInviteRequest) GetInviterUsername() string {
	if x != nil {
		return x.InviterUsername
	}
	return ""
}

// Request to create a group join request notification
type CreateGroupJoinRequestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupOwnerId      int64                  `protobuf:"varint,1,opt,name=group_owner_id,json=groupOwnerId,proto3" json:"group_owner_id,omitempty"`             // recipient (typically the group owner/admin)
	RequesterUserId   int64                  `protobuf:"varint,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`    // user that requested to join
	GroupId           int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                              // id of the group
	GroupName         string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                         // name of the group
	RequesterUsername string                 `protobuf:"bytes,5,opt,name=requester_username,json=requesterUsername,proto3" json:"requester_username,omitempty"` // username of the requester
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateGroupJoinRequestRequest) Reset() {
	*x = CreateGroupJoinRequestRequest{}
	mi := &file_notifications_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupJoinRequestRequest) ProtoMessage() {}

func (x *CreateGroupJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{13}
}

func (x *CreateGroupJoinRequestRequest) GetGroupOwnerId() int64 {
	if x != nil {
		return x.GroupOwnerId
	}
	return 0
}

func (x *CreateGroupJoinRequestRequest) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *CreateGroupJoinRequestRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupJoinRequestRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGroupJoinRequestRequest) GetRequesterUsername() string {
	if x != nil {
		return x.RequesterUsername
	}
	return ""
}

// Request to create a new event notification
type CreateNewEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // recipient
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`         // id of the group
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`         // id of the event
	GroupName     string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`    // name of the group
	EventTitle    string                 `protobuf:"bytes,5,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"` // title of the event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewEventRequest) Reset() {
	*x = CreateNewEventRequest{}
	mi := &file_notifications_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewEventRequest) ProtoMessage() {}

func (x *CreateNewEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewEventRequest.ProtoReflect.Descriptor instead.
func (*CreateNewEventRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{14}
}

func (x *CreateNewEventRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNewEventRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateNewEventRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateNewEventRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateNewEventRequest) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

// Request to create a post like notification
type CreatePostLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // recipient (post owner)
	LikerUserId   int64                  `protobuf:"varint,2,opt,name=liker_user_id,json=likerUserId,proto3" json:"liker_user_id,omitempty"`    // user that liked the post
	PostId        int64                  `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`                     // id of the post
	LikerUsername string                 `protobuf:"bytes,4,opt,name=liker_username,json=likerUsername,proto3" json:"liker_username,omitempty"` // username of the liker
	Aggregate     bool                   `protobuf:"varint,5,opt,name=aggregate,proto3" json:"aggregate,omitempty"`                             // whether to aggregate this notification with existing ones
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostLikeRequest) Reset() {
	*x = CreatePostLikeRequest{}
	mi := &file_notifications_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostLikeRequest) ProtoMessage() {}

func (x *CreatePostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostLikeRequest.ProtoReflect.Descriptor instead.
func (*CreatePostLikeRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePostLikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostLikeRequest) GetLikerUserId() int64 {
	if x != nil {
		return x.LikerUserId
	}
	return 0
}

func (x *CreatePostLikeRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostLikeRequest) GetLikerUsername() string {
	if x != nil {
		return x.LikerUsername
	}
	return ""
}

func (x *CreatePostLikeRequest) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

// Request to create a post comment notification
type CreatePostCommentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                 // recipient (post owner)
	CommenterUserId   int64                  `protobuf:"varint,2,opt,name=commenter_user_id,json=commenterUserId,proto3" json:"commenter_user_id,omitempty"`    // user that commented
	PostId            int64                  `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`                                 // id of the post
	CommenterUsername string                 `protobuf:"bytes,4,opt,name=commenter_username,json=commenterUsername,proto3" json:"commenter_username,omitempty"` // username of the commenter
	CommentContent    string                 `protobuf:"bytes,5,opt,name=comment_content,json=commentContent,proto3" json:"comment_content,omitempty"`          // content of the comment
	Aggregate         bool                   `protobuf:"varint,6,opt,name=aggregate,proto3" json:"aggregate,omitempty"`                                         // whether to aggregate this notification with existing ones
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePostCommentRequest) Reset() {
	*x = CreatePostCommentRequest{}
	mi := &file_notifications_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostCommentRequest) ProtoMessage() {}

func (x *CreatePostCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostCommentRequest.ProtoReflect.Descriptor instead.
func (*CreatePostCommentRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePostCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostCommentRequest) GetCommenterUserId() int64 {
	if x != nil {
		return x.CommenterUserId
	}
	return 0
}

func (x *CreatePostCommentRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostCommentRequest) GetCommenterUsername() string {
	if x != nil {
		return x.CommenterUsername
	}
	return ""
}

func (x *CreatePostCommentRequest) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *CreatePostCommentRequest) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

// Request to create a mention notification
type CreateMentionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                 // recipient (mentioned user)
	MentionerUserId   int64                  `protobuf:"varint,2,opt,name=mentioner_user_id,json=mentionerUserId,proto3" json:"mentioner_user_id,omitempty"`    // user that made the mention
	PostId            int64                  `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`                                 // id of the post where mention occurred
	MentionerUsername string                 `protobuf:"bytes,4,opt,name=mentioner_username,json=mentionerUsername,proto3" json:"mentioner_username,omitempty"` // username of the mentioner
	PostContent       string                 `protobuf:"bytes,5,opt,name=post_content,json=postContent,proto3" json:"post_content,omitempty"`                   // content of the post
	MentionText       string                 `protobuf:"bytes,6,opt,name=mention_text,json=mentionText,proto3" json:"mention_text,omitempty"`                   // the actual text that was mentioned
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateMentionRequest) Reset() {
	*x = CreateMentionRequest{}
	mi := &file_notifications_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMentionRequest) ProtoMessage() {}

func (x *CreateMentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMentionRequest.ProtoReflect.Descriptor instead.
func (*CreateMentionRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{17}
}

func (x *CreateMentionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMentionRequest) GetMentionerUserId() int64 {
	if x != nil {
		return x.MentionerUserId
	}
	return 0
}

func (x *CreateMentionRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateMentionRequest) GetMentionerUsername() string {
	if x != nil {
		return x.MentionerUsername
	}
	return ""
}

func (x *CreateMentionRequest) GetPostContent() string {
	if x != nil {
		return x.PostContent
	}
	return ""
}

func (x *CreateMentionRequest) GetMentionText() string {
	if x != nil {
		return x.MentionText
	}
	return ""
}

// Request to create a new message notification
type CreateNewMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // recipient
	SenderUserId   int64                  `protobuf:"varint,2,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`    // user that sent the message
	ChatId         int64                  `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`                        // id of the chat
	SenderUsername string                 `protobuf:"bytes,4,opt,name=sender_username,json=senderUsername,proto3" json:"sender_username,omitempty"` // username of the sender
	MessageContent string                 `protobuf:"bytes,5,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // content of the message
	Aggregate      bool                   `protobuf:"varint,6,opt,name=aggregate,proto3" json:"aggregate,omitempty"`                                // whether to aggregate this notification with existing ones
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNewMessageRequest) Reset() {
	*x = CreateNewMessageRequest{}
	mi := &file_notifications_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewMessageRequest) ProtoMessage() {}

func (x *CreateNewMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateNewMessageRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{18}
}

func (x *CreateNewMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNewMessageRequest) GetSenderUserId() int64 {
	if x != nil {
		return x.SenderUserId
	}
	return 0
}

func (x *CreateNewMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *CreateNewMessageRequest) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *CreateNewMessageRequest) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *CreateNewMessageRequest) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

// Request to create a follow request accepted notification
type CreateFollowRequestAcceptedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterUserId int64                  `protobuf:"varint,1,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"` // recipient (original requester)
	TargetUserId    int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`          // user that accepted the request
	TargetUsername  string                 `protobuf:"bytes,3,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`       // username of the target user
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateFollowRequestAcceptedRequest) Reset() {
	*x = CreateFollowRequestAcceptedRequest{}
	mi := &file_notifications_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowRequestAcceptedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowRequestAcceptedRequest) ProtoMessage() {}

func (x *CreateFollowRequestAcceptedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowRequestAcceptedRequest.ProtoReflect.Descriptor instead.
func (*CreateFollowRequestAcceptedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{19}
}

func (x *CreateFollowRequestAcceptedRequest) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *CreateFollowRequestAcceptedRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *CreateFollowRequestAcceptedRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

// Request to create a follow request rejected notification
type CreateFollowRequestRejectedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterUserId int64                  `protobuf:"varint,1,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"` // recipient (original requester)
	TargetUserId    int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`          // user that rejected the request
	TargetUsername  string                 `protobuf:"bytes,3,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`       // username of the target user
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateFollowRequestRejectedRequest) Reset() {
	*x = CreateFollowRequestRejectedRequest{}
	mi := &file_notifications_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowRequestRejectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowRequestRejectedRequest) ProtoMessage() {}

func (x *CreateFollowRequestRejectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowRequestRejectedRequest.ProtoReflect.Descriptor instead.
func (*CreateFollowRequestRejectedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{20}
}

func (x *CreateFollowRequestRejectedRequest) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *CreateFollowRequestRejectedRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *CreateFollowRequestRejectedRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

// Request to create a group invite accepted notification
type CreateGroupInviteAcceptedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InviterUserId   int64                  `protobuf:"varint,1,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`    // recipient (original inviter)
	InvitedUserId   int64                  `protobuf:"varint,2,opt,name=invited_user_id,json=invitedUserId,proto3" json:"invited_user_id,omitempty"`    // user that accepted the invite
	GroupId         int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                        // id of the group
	InvitedUsername string                 `protobuf:"bytes,4,opt,name=invited_username,json=invitedUsername,proto3" json:"invited_username,omitempty"` // username of the invited user
	GroupName       string                 `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                   // name of the group
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupInviteAcceptedRequest) Reset() {
	*x = CreateGroupInviteAcceptedRequest{}
	mi := &file_notifications_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupInviteAcceptedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupInviteAcceptedRequest) ProtoMessage() {}

func (x *CreateGroupInviteAcceptedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupInviteAcceptedRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupInviteAcceptedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{21}
}

func (x *CreateGroupInviteAcceptedRequest) GetInviterUserId() int64 {
	if x != nil {
		return x.InviterUserId
	}
	return 0
}

func (x *CreateGroupInviteAcceptedRequest) GetInvitedUserId() int64 {
	if x != nil {
		return x.InvitedUserId
	}
	return 0
}

func (x *CreateGroupInviteAcceptedRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupInviteAcceptedRequest) GetInvitedUsername() string {
	if x != nil {
		return x.InvitedUsername
	}
	return ""
}

func (x *CreateGroupInviteAcceptedRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// Request to create a group invite rejected notification
type CreateGroupInviteRejectedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InviterUserId   int64                  `protobuf:"varint,1,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`    // recipient (original inviter)
	InvitedUserId   int64                  `protobuf:"varint,2,opt,name=invited_user_id,json=invitedUserId,proto3" json:"invited_user_id,omitempty"`    // user that rejected the invite
	GroupId         int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                        // id of the group
	InvitedUsername string                 `protobuf:"bytes,4,opt,name=invited_username,json=invitedUsername,proto3" json:"invited_username,omitempty"` // username of the invited user
	GroupName       string                 `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                   // name of the group
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupInviteRejectedRequest) Reset() {
	*x = CreateGroupInviteRejectedRequest{}
	mi := &file_notifications_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupInviteRejectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupInviteRejectedRequest) ProtoMessage() {}

func (x *CreateGroupInviteRejectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupInviteRejectedRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupInviteRejectedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{22}
}

func (x *CreateGroupInviteRejectedRequest) GetInviterUserId() int64 {
	if x != nil {
		return x.InviterUserId
	}
	return 0
}

func (x *CreateGroupInviteRejectedRequest) GetInvitedUserId() int64 {
	if x != nil {
		return x.InvitedUserId
	}
	return 0
}

func (x *CreateGroupInviteRejectedRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupInviteRejectedRequest) GetInvitedUsername() string {
	if x != nil {
		return x.InvitedUsername
	}
	return ""
}

func (x *CreateGroupInviteRejectedRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// Request to create a group join request accepted notification
type CreateGroupJoinRequestAcceptedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterUserId int64                  `protobuf:"varint,1,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"` // recipient (original requester)
	GroupOwnerId    int64                  `protobuf:"varint,2,opt,name=group_owner_id,json=groupOwnerId,proto3" json:"group_owner_id,omitempty"`          // user that accepted the request (group owner/admin)
	GroupId         int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                           // id of the group
	GroupName       string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                      // name of the group
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupJoinRequestAcceptedRequest) Reset() {
	*x = CreateGroupJoinRequestAcceptedRequest{}
	mi := &file_notifications_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupJoinRequestAcceptedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupJoinRequestAcceptedRequest) ProtoMessage() {}

func (x *CreateGroupJoinRequestAcceptedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupJoinRequestAcceptedRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupJoinRequestAcceptedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{23}
}

func (x *CreateGroupJoinRequestAcceptedRequest) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *CreateGroupJoinRequestAcceptedRequest) GetGroupOwnerId() int64 {
	if x != nil {
		return x.GroupOwnerId
	}
	return 0
}

func (x *CreateGroupJoinRequestAcceptedRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupJoinRequestAcceptedRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// Request to create a group join request rejected notification
type CreateGroupJoinRequestRejectedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterUserId int64                  `protobuf:"varint,1,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"` // recipient (original requester)
	GroupOwnerId    int64                  `protobuf:"varint,2,opt,name=group_owner_id,json=groupOwnerId,proto3" json:"group_owner_id,omitempty"`          // user that rejected the request (group owner/admin)
	GroupId         int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                           // id of the group
	GroupName       string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                      // name of the group
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupJoinRequestRejectedRequest) Reset() {
	*x = CreateGroupJoinRequestRejectedRequest{}
	mi := &file_notifications_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupJoinRequestRejectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupJoinRequestRejectedRequest) ProtoMessage() {}

func (x *CreateGroupJoinRequestRejectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupJoinRequestRejectedRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupJoinRequestRejectedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{24}
}

func (x *CreateGroupJoinRequestRejectedRequest) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *CreateGroupJoinRequestRejectedRequest) GetGroupOwnerId() int64 {
	if x != nil {
		return x.GroupOwnerId
	}
	return 0
}

func (x *CreateGroupJoinRequestRejectedRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupJoinRequestRejectedRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

var File_notifications_proto protoreflect.FileDescriptor

const file_notifications_proto_rawDesc = "" +
	"\n" +
	"\x13notifications.proto\x12\rnotifications\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xed\x04\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12%\n" +
	"\x0esource_service\x18\x06 \x01(\tR\rsourceService\x12(\n" +
	"\x10source_entity_id\x18\a \x01(\x03R\x0esourceEntityId\x12!\n" +
	"\fneeds_action\x18\b \x01(\bR\vneedsAction\x12\x14\n" +
	"\x05acted\x18\t \x01(\bR\x05acted\x12\x14\n" +
	"\x05count\x18\n" +
	" \x01(\x05R\x05count\x12B\n" +
	"\apayload\x18\v \x03(\v2(.notifications.Notification.PayloadEntryR\apayload\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\x06status\x18\x0e \x01(\x0e2!.notifications.NotificationStatusR\x06status\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x03\n" +
	"\x19CreateNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12%\n" +
	"\x0esource_service\x18\x05 \x01(\tR\rsourceService\x12(\n" +
	"\x10source_entity_id\x18\x06 \x01(\x03R\x0esourceEntityId\x12!\n" +
	"\fneeds_action\x18\a \x01(\bR\vneedsAction\x12O\n" +
	"\apayload\x18\b \x03(\v25.notifications.CreateNotificationRequest.PayloadEntryR\apayload\x12\x1c\n" +
	"\taggregate\x18\t \x01(\bR\taggregate\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x1aCreateNotificationsRequest\x12N\n" +
	"\rnotifications\x18\x01 \x03(\v2(.notifications.CreateNotificationRequestR\rnotifications\"o\n" +
	"\x1bCreateNotificationsResponse\x12P\n" +
	"\x15created_notifications\x18\x01 \x03(\v2\x1b.notifications.NotificationR\x14createdNotifications\"\xbc\x01\n" +
	"\x1bGetUserNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x125\n" +
	"\x05types\x18\x04 \x03(\x0e2\x1f.notifications.NotificationTypeR\x05types\x12\x1f\n" +
	"\vunread_only\x18\x05 \x01(\bR\n" +
	"unreadOnly\"\xa5\x01\n" +
	"\x1cGetUserNotificationsResponse\x12A\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1b.notifications.NotificationR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\funread_count\x18\x03 \x01(\x05R\vunreadCount\"a\n" +
	"\x1dMarkNotificationAsReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"]\n" +
	"\x19DeleteNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xcd\x01\n" +
	"\x17NotificationPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12Y\n" +
	"\vpreferences\x18\x02 \x03(\v27.notifications.NotificationPreferences.PreferencesEntryR\vpreferences\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xe7\x01\n" +
	"$UpdateNotificationPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12f\n" +
	"\vpreferences\x18\x02 \x03(\v2D.notifications.UpdateNotificationPreferencesRequest.PreferencesEntryR\vpreferences\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x1aCreateFollowRequestRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\x03R\x0frequesterUserId\x12-\n" +
	"\x12requester_username\x18\x03 \x01(\tR\x11requesterUsername\"\xb5\x01\n" +
	"\x18CreateNewFollowerRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12(\n" +
	"\x10follower_user_id\x18\x02 \x01(\x03R\x0efollowerUserId\x12+\n" +
	"\x11follower_username\x18\x03 \x01(\tR\x10followerUsername\x12\x1c\n" +
	"\taggregate\x18\x04 \x01(\bR\taggregate\"\xcf\x01\n" +
	"\x18CreateGroupInviteRequest\x12&\n" +
	"\x0finvited_user_id\x18\x01 \x01(\x03R\rinvitedUserId\x12&\n" +
	"\x0finviter_user_id\x18\x02 \x01(\x03R\rinviterUserId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12)\n" +
	"\x10inviter_username\x18\x05 \x01(\tR\x0finviterUsername\"\xda\x01\n" +
	"\x1dCreateGroupJoinRequestRequest\x12$\n" +
	"\x0egroup_owner_id\x18\x01 \x01(\x03R\fgroupOwnerId\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\x03R\x0frequesterUserId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12-\n" +
	"\x12requester_username\x18\x05 \x01(\tR\x11requesterUsername\"\xa6\x01\n" +
	"\x15CreateNewEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12\x1f\n" +
	"\vevent_title\x18\x05 \x01(\tR\n" +
	"eventTitle\"\xb2\x01\n" +
	"\x15CreatePostLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\"\n" +
	"\rliker_user_id\x18\x02 \x01(\x03R\vlikerUserId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\x12%\n" +
	"\x0eliker_username\x18\x04 \x01(\tR\rlikerUsername\x12\x1c\n" +
	"\taggregate\x18\x05 \x01(\bR\taggregate\"\xee\x01\n" +
	"\x18CreatePostCommentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12*\n" +
	"\x11commenter_user_id\x18\x02 \x01(\x03R\x0fcommenterUserId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\x12-\n" +
	"\x12commenter_username\x18\x04 \x01(\tR\x11commenterUsername\x12'\n" +
	"\x0fcomment_content\x18\x05 \x01(\tR\x0ecommentContent\x12\x1c\n" +
	"\taggregate\x18\x06 \x01(\bR\taggregate\"\xe9\x01\n" +
	"\x14CreateMentionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12*\n" +
	"\x11mentioner_user_id\x18\x02 \x01(\x03R\x0fmentionerUserId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\x12-\n" +
	"\x12mentioner_username\x18\x04 \x01(\tR\x11mentionerUsername\x12!\n" +
	"\fpost_content\x18\x05 \x01(\tR\vpostContent\x12!\n" +
	"\fmention_text\x18\x06 \x01(\tR\vmentionText\"\xe1\x01\n" +
	"\x17CreateNewMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\x0esender_user_id\x18\x02 \x01(\x03R\fsenderUserId\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x03R\x06chatId\x12'\n" +
	"\x0fsender_username\x18\x04 \x01(\tR\x0esenderUsername\x12'\n" +
	"\x0fmessage_content\x18\x05 \x01(\tR\x0emessageContent\x12\x1c\n" +
	"\taggregate\x18\x06 \x01(\bR\taggregate\"\x9f\x01\n" +
	"\"CreateFollowRequestAcceptedRequest\x12*\n" +
	"\x11requester_user_id\x18\x01 \x01(\x03R\x0frequesterUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\x12'\n" +
	"\x0ftarget_username\x18\x03 \x01(\tR\x0etargetUsername\"\x9f\x01\n" +
	"\"CreateFollowRequestRejectedRequest\x12*\n" +
	"\x11requester_user_id\x18\x01 \x01(\x03R\x0frequesterUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\x12'\n" +
	"\x0ftarget_username\x18\x03 \x01(\tR\x0etargetUsername\"\xd7\x01\n" +
	" CreateGroupInviteAcceptedRequest\x12&\n" +
	"\x0finviter_user_id\x18\x01 \x01(\x03R\rinviterUserId\x12&\n" +
	"\x0finvited_user_id\x18\x02 \x01(\x03R\rinvitedUserId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12)\n" +
	"\x10invited_username\x18\x04 \x01(\tR\x0finvitedUsername\x12\x1d\n" +
	"\n" +
	"group_name\x18\x05 \x01(\tR\tgroupName\"\xd7\x01\n" +
	" CreateGroupInviteRejectedRequest\x12&\n" +
	"\x0finviter_user_id\x18\x01 \x01(\x03R\rinviterUserId\x12&\n" +
	"\x0finvited_user_id\x18\x02 \x01(\x03R\rinvitedUserId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12)\n" +
	"\x10invited_username\x18\x04 \x01(\tR\x0finvitedUsername\x12\x1d\n" +
	"\n" +
	"group_name\x18\x05 \x01(\tR\tgroupName\"\xb3\x01\n" +
	"%CreateGroupJoinRequestAcceptedRequest\x12*\n" +
	"\x11requester_user_id\x18\x01 \x01(\x03R\x0frequesterUserId\x12$\n" +
	"\x0egroup_owner_id\x18\x02 \x01(\x03R\fgroupOwnerId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\"\xb3\x01\n" +
	"%CreateGroupJoinRequestRejectedRequest\x12*\n" +
	"\x11requester_user_id\x18\x01 \x01(\x03R\x0frequesterUserId\x12$\n" +
	"\x0egroup_owner_id\x18\x02 \x01(\x03R\fgroupOwnerId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName*\x93\x05\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" NOTIFICATION_TYPE_FOLLOW_REQUEST\x10\x01\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_NEW_FOLLOWER\x10\x02\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_GROUP_INVITE\x10\x03\x12(\n" +
	"$NOTIFICATION_TYPE_GROUP_JOIN_REQUEST\x10\x04\x12\x1f\n" +
	"\x1bNOTIFICATION_TYPE_NEW_EVENT\x10\x05\x12\x1f\n" +
	"\x1bNOTIFICATION_TYPE_POST_LIKE\x10\x06\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_POST_COMMENT\x10\a\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_MENTION\x10\b\x12!\n" +
	"\x1dNOTIFICATION_TYPE_NEW_MESSAGE\x10\t\x12-\n" +
	")NOTIFICATION_TYPE_FOLLOW_REQUEST_ACCEPTED\x10\n" +
	"\x12-\n" +
	")NOTIFICATION_TYPE_FOLLOW_REQUEST_REJECTED\x10\v\x12+\n" +
	"'NOTIFICATION_TYPE_GROUP_INVITE_ACCEPTED\x10\f\x12+\n" +
	"'NOTIFICATION_TYPE_GROUP_INVITE_REJECTED\x10\r\x121\n" +
	"-NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_ACCEPTED\x10\x0e\x121\n" +
	"-NOTIFICATION_TYPE_GROUP_JOIN_REQUEST_REJECTED\x10\x0f*\x98\x01\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_UNREAD\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_READ\x10\x02\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_DELETED\x10\x032\xc2\x12\n" +
	"\x13NotificationService\x12[\n" +
	"\x12CreateNotification\x12(.notifications.CreateNotificationRequest\x1a\x1b.notifications.Notification\x12l\n" +
	"\x13CreateNotifications\x12).notifications.CreateNotificationsRequest\x1a*.notifications.CreateNotificationsResponse\x12]\n" +
	"\x13CreateFollowRequest\x12).notifications.CreateFollowRequestRequest\x1a\x1b.notifications.Notification\x12Y\n" +
	"\x11CreateNewFollower\x12'.notifications.CreateNewFollowerRequest\x1a\x1b.notifications.Notification\x12Y\n" +
	"\x11CreateGroupInvite\x12'.notifications.CreateGroupInviteRequest\x1a\x1b.notifications.Notification\x12c\n" +
	"\x16CreateGroupJoinRequest\x12,.notifications.CreateGroupJoinRequestRequest\x1a\x1b.notifications.Notification\x12S\n" +
	"\x0eCreateNewEvent\x12$.notifications.CreateNewEventRequest\x1a\x1b.notifications.Notification\x12S\n" +
	"\x0eCreatePostLike\x12$.notifications.CreatePostLikeRequest\x1a\x1b.notifications.Notification\x12Y\n" +
	"\x11CreatePostComment\x12'.notifications.CreatePostCommentRequest\x1a\x1b.notifications.Notification\x12Q\n" +
	"\rCreateMention\x12#.notifications.CreateMentionRequest\x1a\x1b.notifications.Notification\x12W\n" +
	"\x10CreateNewMessage\x12&.notifications.CreateNewMessageRequest\x1a\x1b.notifications.Notification\x12m\n" +
	"\x1bCreateFollowRequestAccepted\x121.notifications.CreateFollowRequestAcceptedRequest\x1a\x1b.notifications.Notification\x12m\n" +
	"\x1bCreateFollowRequestRejected\x121.notifications.CreateFollowRequestRejectedRequest\x1a\x1b.notifications.Notification\x12i\n" +
	"\x19CreateGroupInviteAccepted\x12/.notifications.CreateGroupInviteAcceptedRequest\x1a\x1b.notifications.Notification\x12i\n" +
	"\x19CreateGroupInviteRejected\x12/.notifications.CreateGroupInviteRejectedRequest\x1a\x1b.notifications.Notification\x12s\n" +
	"\x1eCreateGroupJoinRequestAccepted\x124.notifications.CreateGroupJoinRequestAcceptedRequest\x1a\x1b.notifications.Notification\x12s\n" +
	"\x1eCreateGroupJoinRequestRejected\x124.notifications.CreateGroupJoinRequestRejectedRequest\x1a\x1b.notifications.Notification\x12o\n" +
	"\x14GetUserNotifications\x12*.notifications.GetUserNotificationsRequest\x1a+.notifications.GetUserNotificationsResponse\x12W\n" +
	"\x1bGetUnreadNotificationsCount\x12\x1b.google.protobuf.Int64Value\x1a\x1b.google.protobuf.Int64Value\x12^\n" +
	"\x16MarkNotificationAsRead\x12,.notifications.MarkNotificationAsReadRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\rMarkAllAsRead\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x12DeleteNotification\x12(.notifications.DeleteNotificationRequest\x1a\x16.google.protobuf.Empty\x12a\n" +
	"\x1aGetNotificationPreferences\x12\x1b.google.protobuf.Int64Value\x1a&.notifications.NotificationPreferences\x12l\n" +
	"\x1dUpdateNotificationPreferences\x123.notifications.UpdateNotificationPreferencesRequest\x1a\x16.google.protobuf.EmptyB:Z8social-network/shared/gen-go/notifications;notificationsb\x06proto3"

var (
	file_notifications_proto_rawDescOnce sync.Once
	file_notifications_proto_rawDescData []byte
)

func file_notifications_proto_rawDescGZIP() []byte {
	file_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)))
	})
	return file_notifications_proto_rawDescData
}

var file_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_notifications_proto_goTypes = []any{
	(NotificationType)(0),                         // 0: notifications.NotificationType
	(NotificationStatus)(0),                       // 1: notifications.NotificationStatus
	(*Notification)(nil),                          // 2: notifications.Notification
	(*CreateNotificationRequest)(nil),             // 3: notifications.CreateNotificationRequest
	(*CreateNotificationsRequest)(nil),            // 4: notifications.CreateNotificationsRequest
	(*CreateNotificationsResponse)(nil),           // 5: notifications.CreateNotificationsResponse
	(*GetUserNotificationsRequest)(nil),           // 6: notifications.GetUserNotificationsRequest
	(*GetUserNotificationsResponse)(nil),          // 7: notifications.GetUserNotificationsResponse
	(*MarkNotificationAsReadRequest)(nil),         // 8: notifications.MarkNotificationAsReadRequest
	(*DeleteNotificationRequest)(nil),             // 9: notifications.DeleteNotificationRequest
	(*NotificationPreferences)(nil),               // 10: notifications.NotificationPreferences
	(*UpdateNotificationPreferencesRequest)(nil),  // 11: notifications.UpdateNotificationPreferencesRequest
	(*CreateFollowRequestRequest)(nil),            // 12: notifications.CreateFollowRequestRequest
	(*CreateNewFollowerRequest)(nil),              // 13: notifications.CreateNewFollowerRequest
	(*CreateGroupInviteRequest)(nil),              // 14: notifications.CreateGroupInviteRequest
	(*CreateGroupJoinRequestRequest)(nil),         // 15: notifications.CreateGroupJoinRequestRequest
	(*CreateNewEventRequest)(nil),                 // 16: notifications.CreateNewEventRequest
	(*CreatePostLikeRequest)(nil),                 // 17: notifications.CreatePostLikeRequest
	(*CreatePostCommentRequest)(nil),              // 18: notifications.CreatePostCommentRequest
	(*CreateMentionRequest)(nil),                  // 19: notifications.CreateMentionRequest
	(*CreateNewMessageRequest)(nil),               // 20: notifications.CreateNewMessageRequest
	(*CreateFollowRequestAcceptedRequest)(nil),    // 21: notifications.CreateFollowRequestAcceptedRequest
	(*CreateFollowRequestRejectedRequest)(nil),    // 22: notifications.CreateFollowRequestRejectedRequest
	(*CreateGroupInviteAcceptedRequest)(nil),      // 23: notifications.CreateGroupInviteAcceptedRequest
	(*CreateGroupInviteRejectedRequest)(nil),      // 24: notifications.CreateGroupInviteRejectedRequest
	(*CreateGroupJoinRequestAcceptedRequest)(nil), // 25: notifications.CreateGroupJoinRequestAcceptedRequest
	(*CreateGroupJoinRequestRejectedRequest)(nil), // 26: notifications.CreateGroupJoinRequestRejectedRequest
	nil,                           // 27: notifications.Notification.PayloadEntry
	nil,                           // 28: notifications.CreateNotificationRequest.PayloadEntry
	nil,                           // 29: notifications.NotificationPreferences.PreferencesEntry
	nil,                           // 30: notifications.UpdateNotificationPreferencesRequest.PreferencesEntry
	(*timestamppb.Timestamp)(nil), // 31: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil), // 32: google.protobuf.Int64Value
	(*emptypb.Empty)(nil),         // 33: google.protobuf.Empty
}
var file_notifications_proto_depIdxs = []int32{
	0,  // 0: notifications.Notification.type:type_name -> notifications.NotificationType
	27, // 1: notifications.Notification.payload:type_name -> notifications.Notification.PayloadEntry
	31, // 2: notifications.Notification.created_at:type_name -> google.protobuf.Timestamp
	31, // 3: notifications.Notification.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 4: notifications.Notification.status:type_name -> notifications.NotificationStatus
	0,  // 5: notifications.CreateNotificationRequest.type:type_name -> notifications.NotificationType
	28, // 6: notifications.CreateNotificationRequest.payload:type_name -> notifications.CreateNotificationRequest.PayloadEntry
	3,  // 7: notifications.CreateNotificationsRequest.notifications:type_name -> notifications.CreateNotificationRequest
	2,  // 8: notifications.CreateNotificationsResponse.created_notifications:type_name -> notifications.Notification
	0,  // 9: notifications.GetUserNotificationsRequest.types:type_name -> notifications.NotificationType
	2,  // 10: notifications.GetUserNotificationsResponse.notifications:type_name -> notifications.Notification
	29, // 11: notifications.NotificationPreferences.preferences:type_name -> notifications.NotificationPreferences.PreferencesEntry
	30, // 12: notifications.UpdateNotificationPreferencesRequest.preferences:type_name -> notifications.UpdateNotificationPreferencesRequest.PreferencesEntry
	3,  // 13: notifications.NotificationService.CreateNotification:input_type -> notifications.CreateNotificationRequest
	4,  // 14: notifications.NotificationService.CreateNotifications:input_type -> notifications.CreateNotificationsRequest
	12, // 15: notifications.NotificationService.CreateFollowRequest:input_type -> notifications.CreateFollowRequestRequest
	13, // 16: notifications.NotificationService.CreateNewFollower:input_type -> notifications.CreateNewFollowerRequest
	14, // 17: notifications.NotificationService.CreateGroupInvite:input_type -> notifications.CreateGroupInviteRequest
	15, // 18: notifications.NotificationService.CreateGroupJoinRequest:input_type -> notifications.CreateGroupJoinRequestRequest
	16, // 19: notifications.NotificationService.CreateNewEvent:input_type -> notifications.CreateNewEventRequest
	17, // 20: notifications.NotificationService.CreatePostLike:input_type -> notifications.CreatePostLikeRequest
	18, // 21: notifications.NotificationService.CreatePostComment:input_type -> notifications.CreatePostCommentRequest
	19, // 22: notifications.NotificationService.CreateMention:input_type -> notifications.CreateMentionRequest
	20, // 23: notifications.NotificationService.CreateNewMessage:input_type -> notifications.CreateNewMessageRequest
	21, // 24: notifications.NotificationService.CreateFollowRequestAccepted:input_type -> notifications.CreateFollowRequestAcceptedRequest
	22, // 25: notifications.NotificationService.CreateFollowRequestRejected:input_type -> notifications.CreateFollowRequestRejectedRequest
	23, // 26: notifications.NotificationService.CreateGroupInviteAccepted:input_type -> notifications.CreateGroupInviteAcceptedRequest
	24, // 27: notifications.NotificationService.CreateGroupInviteRejected:input_type -> notifications.CreateGroupInviteRejectedRequest
	25, // 28: notifications.NotificationService.CreateGroupJoinRequestAccepted:input_type -> notifications.CreateGroupJoinRequestAcceptedRequest
	26, // 29: notifications.NotificationService.CreateGroupJoinRequestRejected:input_type -> notifications.CreateGroupJoinRequestRejectedRequest
	6,  // 30: notifications.NotificationService.GetUserNotifications:input_type -> notifications.GetUserNotificationsRequest
	32, // 31: notifications.NotificationService.GetUnreadNotificationsCount:input_type -> google.protobuf.Int64Value
	8,  // 32: notifications.NotificationService.MarkNotificationAsRead:input_type -> notifications.MarkNotificationAsReadRequest
	32, // 33: notifications.NotificationService.MarkAllAsRead:input_type -> google.protobuf.Int64Value
	9,  // 34: notifications.NotificationService.DeleteNotification:input_type -> notifications.DeleteNotificationRequest
	32, // 35: notifications.NotificationService.GetNotificationPreferences:input_type -> google.protobuf.Int64Value
	11, // 36: notifications.NotificationService.UpdateNotificationPreferences:input_type -> notifications.UpdateNotificationPreferencesRequest
	2,  // 37: notifications.NotificationService.CreateNotification:output_type -> notifications.Notification
	5,  // 38: notifications.NotificationService.CreateNotifications:output_type -> notifications.CreateNotificationsResponse
	2,  // 39: notifications.NotificationService.CreateFollowRequest:output_type -> notifications.Notification
	2,  // 40: notifications.NotificationService.CreateNewFollower:output_type -> notifications.Notification
	2,  // 41: notifications.NotificationService.CreateGroupInvite:output_type -> notifications.Notification
	2,  // 42: notifications.NotificationService.CreateGroupJoinRequest:output_type -> notifications.Notification
	2,  // 43: notifications.NotificationService.CreateNewEvent:output_type -> notifications.Notification
	2,  // 44: notifications.NotificationService.CreatePostLike:output_type -> notifications.Notification
	2,  // 45: notifications.NotificationService.CreatePostComment:output_type -> notifications.Notification
	2,  // 46: notifications.NotificationService.CreateMention:output_type -> notifications.Notification
	2,  // 47: notifications.NotificationService.CreateNewMessage:output_type -> notifications.Notification
	2,  // 48: notifications.NotificationService.CreateFollowRequestAccepted:output_type -> notifications.Notification
	2,  // 49: notifications.NotificationService.CreateFollowRequestRejected:output_type -> notifications.Notification
	2,  // 50: notifications.NotificationService.CreateGroupInviteAccepted:output_type -> notifications.Notification
	2,  // 51: notifications.NotificationService.CreateGroupInviteRejected:output_type -> notifications.Notification
	2,  // 52: notifications.NotificationService.CreateGroupJoinRequestAccepted:output_type -> notifications.Notification
	2,  // 53: notifications.NotificationService.CreateGroupJoinRequestRejected:output_type -> notifications.Notification
	7,  // 54: notifications.NotificationService.GetUserNotifications:output_type -> notifications.GetUserNotificationsResponse
	32, // 55: notifications.NotificationService.GetUnreadNotificationsCount:output_type -> google.protobuf.Int64Value
	33, // 56: notifications.NotificationService.MarkNotificationAsRead:output_type -> google.protobuf.Empty
	33, // 57: notifications.NotificationService.MarkAllAsRead:output_type -> google.protobuf.Empty
	33, // 58: notifications.NotificationService.DeleteNotification:output_type -> google.protobuf.Empty
	10, // 59: notifications.NotificationService.GetNotificationPreferences:output_type -> notifications.NotificationPreferences
	33, // 60: notifications.NotificationService.UpdateNotificationPreferences:output_type -> google.protobuf.Empty
	37, // [37:61] is the sub-list for method output_type
	13, // [13:37] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_notifications_proto_init() }
func file_notifications_proto_init() {
	if File_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_proto_depIdxs,
		EnumInfos:         file_notifications_proto_enumTypes,
		MessageInfos:      file_notifications_proto_msgTypes,
	}.Build()
	File_notifications_proto = out.File
	file_notifications_proto_goTypes = nil
	file_notifications_proto_depIdxs = nil
}
