// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :exec

INSERT INTO events (
    event_title,
    event_body,
    event_creator_id,
    group_id,
    event_date
)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEventParams struct {
	EventTitle     string
	EventBody      string
	EventCreatorID int64
	GroupID        int64
	EventDate      pgtype.Date
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.EventTitle,
		arg.EventBody,
		arg.EventCreatorID,
		arg.GroupID,
		arg.EventDate,
	)
	return err
}

const deleteEvent = `-- name: DeleteEvent :execrows
UPDATE events
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventResponse = `-- name: DeleteEventResponse :execrows
UPDATE event_responses
SET deleted_at = CURRENT_TIMESTAMP
WHERE event_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type DeleteEventResponseParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) DeleteEventResponse(ctx context.Context, arg DeleteEventResponseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventResponse, arg.EventID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const editEvent = `-- name: EditEvent :execrows
UPDATE events
SET event_title = $1,
    event_body = $2,
    event_date = $3
WHERE id = $4 AND deleted_at IS NULL
`

type EditEventParams struct {
	EventTitle string
	EventBody  string
	EventDate  pgtype.Date
	ID         int64
}

func (q *Queries) EditEvent(ctx context.Context, arg EditEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, editEvent,
		arg.EventTitle,
		arg.EventBody,
		arg.EventDate,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventsByGroupId = `-- name: GetEventsByGroupId :many
SELECT
    e.id,
    e.event_title,
    e.event_body,
    e.event_creator_id,
    e.group_id,
    e.event_date,
    e.created_at,
    e.updated_at,
    e.going_count,
    e.not_going_count,

    (SELECT i.id
     FROM images i
     WHERE i.parent_id = e.id AND i.deleted_at IS NULL
     ORDER BY i.sort_order ASC
     LIMIT 1
    ) AS image


FROM events e
WHERE e.group_id = $1
  AND e.deleted_at IS NULL
  AND e.event_date >= CURRENT_DATE
ORDER BY e.event_date ASC
OFFSET $2
LIMIT $3
`

type GetEventsByGroupIdParams struct {
	GroupID int64
	Offset  int32
	Limit   int32
}

type GetEventsByGroupIdRow struct {
	ID             int64
	EventTitle     string
	EventBody      string
	EventCreatorID int64
	GroupID        int64
	EventDate      pgtype.Date
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	GoingCount     int32
	NotGoingCount  int32
	Image          int64
}

func (q *Queries) GetEventsByGroupId(ctx context.Context, arg GetEventsByGroupIdParams) ([]GetEventsByGroupIdRow, error) {
	rows, err := q.db.Query(ctx, getEventsByGroupId, arg.GroupID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsByGroupIdRow{}
	for rows.Next() {
		var i GetEventsByGroupIdRow
		if err := rows.Scan(
			&i.ID,
			&i.EventTitle,
			&i.EventBody,
			&i.EventCreatorID,
			&i.GroupID,
			&i.EventDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoingCount,
			&i.NotGoingCount,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
