// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (
    event_title,
    event_body,
    event_creator_id,
    group_id,
    event_date,
    still_valid
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_title, event_body, event_creator_id, group_id, event_date, still_valid, going_count, not_going_count, images_count, created_at, updated_at, deleted_at
`

type CreateEventParams struct {
	EventTitle     string
	EventBody      string
	EventCreatorID int64
	GroupID        int64
	EventDate      pgtype.Date
	StillValid     pgtype.Bool
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.EventTitle,
		arg.EventBody,
		arg.EventCreatorID,
		arg.GroupID,
		arg.EventDate,
		arg.StillValid,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventTitle,
		&i.EventBody,
		&i.EventCreatorID,
		&i.GroupID,
		&i.EventDate,
		&i.StillValid,
		&i.GoingCount,
		&i.NotGoingCount,
		&i.ImagesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :one
UPDATE events
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, event_title, event_body, event_creator_id, group_id, event_date, still_valid, going_count, not_going_count, images_count, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, deleteEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventTitle,
		&i.EventBody,
		&i.EventCreatorID,
		&i.GroupID,
		&i.EventDate,
		&i.StillValid,
		&i.GoingCount,
		&i.NotGoingCount,
		&i.ImagesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEventResponse = `-- name: DeleteEventResponse :one
UPDATE event_responses
SET deleted_at = CURRENT_TIMESTAMP
WHERE event_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, event_id, user_id, going, created_at, updated_at, deleted_at
`

type DeleteEventResponseParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) DeleteEventResponse(ctx context.Context, arg DeleteEventResponseParams) (EventResponse, error) {
	row := q.db.QueryRow(ctx, deleteEventResponse, arg.EventID, arg.UserID)
	var i EventResponse
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Going,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const editEvent = `-- name: EditEvent :one
UPDATE events
SET event_title = $1,
    event_body = $2,
    event_date = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, event_title, event_body, event_creator_id, group_id, event_date, still_valid, going_count, not_going_count, images_count, created_at, updated_at, deleted_at
`

type EditEventParams struct {
	EventTitle string
	EventBody  string
	EventDate  pgtype.Date
	ID         int64
}

func (q *Queries) EditEvent(ctx context.Context, arg EditEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, editEvent,
		arg.EventTitle,
		arg.EventBody,
		arg.EventDate,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventTitle,
		&i.EventBody,
		&i.EventCreatorID,
		&i.GroupID,
		&i.EventDate,
		&i.StillValid,
		&i.GoingCount,
		&i.NotGoingCount,
		&i.ImagesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEventsByGroupId = `-- name: GetEventsByGroupId :many
SELECT
    e.id,
    e.event_title,
    e.event_body,
    e.event_creator_id,
    e.group_id,
    e.event_date,
    e.created_at,
    e.updated_at,
    e.going_count,
    e.not_going_count,

    (SELECT i.file_name
     FROM images i
     WHERE i.entity_id = e.id AND i.deleted_at IS NULL
     ORDER BY i.sort_order ASC
     LIMIT 1
    ) AS preview_image,

    (SELECT COUNT(1)
     FROM images i
     WHERE i.entity_id = e.id AND i.deleted_at IS NULL
    ) AS total_images

FROM events e
WHERE e.group_id = $1
  AND e.deleted_at IS NULL
  AND e.event_date >= CURRENT_DATE
ORDER BY e.event_date ASC
OFFSET $2
LIMIT $3
`

type GetEventsByGroupIdParams struct {
	GroupID int64
	Offset  int32
	Limit   int32
}

type GetEventsByGroupIdRow struct {
	ID             int64
	EventTitle     string
	EventBody      string
	EventCreatorID int64
	GroupID        int64
	EventDate      pgtype.Date
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	GoingCount     int32
	NotGoingCount  int32
	PreviewImage   string
	TotalImages    int64
}

func (q *Queries) GetEventsByGroupId(ctx context.Context, arg GetEventsByGroupIdParams) ([]GetEventsByGroupIdRow, error) {
	rows, err := q.db.Query(ctx, getEventsByGroupId, arg.GroupID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsByGroupIdRow{}
	for rows.Next() {
		var i GetEventsByGroupIdRow
		if err := rows.Scan(
			&i.ID,
			&i.EventTitle,
			&i.EventBody,
			&i.EventCreatorID,
			&i.GroupID,
			&i.EventDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoingCount,
			&i.NotGoingCount,
			&i.PreviewImage,
			&i.TotalImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const respondToEvent = `-- name: RespondToEvent :one
INSERT INTO event_responses (event_id, user_id, going)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id)
DO UPDATE
SET going = EXCLUDED.going,
    deleted_at = NULL,           -- restore if it was soft-deleted
    updated_at = CURRENT_TIMESTAMP
RETURNING id, event_id, user_id, going, created_at, updated_at, deleted_at
`

type RespondToEventParams struct {
	EventID int64
	UserID  int64
	Going   bool
}

func (q *Queries) RespondToEvent(ctx context.Context, arg RespondToEventParams) (EventResponse, error) {
	row := q.db.QueryRow(ctx, respondToEvent, arg.EventID, arg.UserID, arg.Going)
	var i EventResponse
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Going,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateStillValid = `-- name: UpdateStillValid :exec
UPDATE events
SET still_valid = FALSE
WHERE event_date < CURRENT_DATE
  AND still_valid = TRUE
`

// needs to be run periodically, eg every day
func (q *Queries) UpdateStillValid(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateStillValid)
	return err
}
