// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package sqlc

import (
	"context"
)

const deleteImage = `-- name: DeleteImage :exec
UPDATE images
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getImages = `-- name: GetImages :one
SELECT id
FROM images
WHERE parent_id = $1
  AND deleted_at IS NULL
ORDER BY sort_order
  LIMIT 1
`

func (q *Queries) GetImages(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getImages, parentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImage = `-- name: InsertImage :exec
INSERT INTO images (id, parent_id)
VALUES ($2::BIGINT, $1::BIGINT)
`

type InsertImageParams struct {
	Column1 int64
	Column2 int64
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) error {
	_, err := q.db.Exec(ctx, insertImage, arg.Column1, arg.Column2)
	return err
}
