// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserReactionForEntityId = `-- name: GetUserReactionForEntityId :one
SELECT 1 FROM reactions r
WHERE r.content_id = p.id
AND r.user_id = $1
AND r.deleted_at IS NULL
`

func (q *Queries) GetUserReactionForEntityId(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getUserReactionForEntityId, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getWhoLikedEntityId = `-- name: GetWhoLikedEntityId :many
SELECT user_id
FROM reactions
WHERE content_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWhoLikedEntityId(ctx context.Context, contentID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getWhoLikedEntityId, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReaction = `-- name: InsertReaction :one
INSERT INTO reactions (content_id, user_id)
VALUES ($1, $2)
RETURNING id, content_id, user_id, deleted_at, updated_at
`

type InsertReactionParams struct {
	ContentID int64
	UserID    int64
}

type InsertReactionRow struct {
	ID        int64
	ContentID int64
	UserID    int64
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertReaction(ctx context.Context, arg InsertReactionParams) (InsertReactionRow, error) {
	row := q.db.QueryRow(ctx, insertReaction, arg.ContentID, arg.UserID)
	var i InsertReactionRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.UserID,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const toggleReactionIfExists = `-- name: ToggleReactionIfExists :one
UPDATE reactions
SET deleted_at = CASE
                     WHEN deleted_at IS NULL THEN NOW()   -- make inactive
                     ELSE NULL                           -- restore
                 END,
    updated_at = NOW()
WHERE content_id = $1
  AND user_id = $2
RETURNING id, content_id, user_id, deleted_at, updated_at
`

type ToggleReactionIfExistsParams struct {
	ContentID int64
	UserID    int64
}

type ToggleReactionIfExistsRow struct {
	ID        int64
	ContentID int64
	UserID    int64
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ToggleReactionIfExists(ctx context.Context, arg ToggleReactionIfExistsParams) (ToggleReactionIfExistsRow, error) {
	row := q.db.QueryRow(ctx, toggleReactionIfExists, arg.ContentID, arg.UserID)
	var i ToggleReactionIfExistsRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.UserID,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
