@baseUrl = http://localhost:8081

### 1) LOGIN
POST {{baseUrl}}/login
Content-Type: application/json

{
  "identifier": "myuser1234",
  "password": "superSecret123"
}

### 2) LOGOUT
POST {{baseUrl}}/logout
Content-Type: application/json

### 3) REGISTER (multipart form-data)
POST {{baseUrl}}/register
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="username"

myuser1234
--BOUNDARY
Content-Disposition: form-data; name="first_name"

John
--BOUNDARY
Content-Disposition: form-data; name="last_name"

Doe
--BOUNDARY
Content-Disposition: form-data; name="date_of_birth"

1999-01-01
--BOUNDARY
Content-Disposition: form-data; name="about"

I love coding!
--BOUNDARY
Content-Disposition: form-data; name="public"

true
--BOUNDARY
Content-Disposition: form-data; name="email"

john2@example.com
--BOUNDARY
Content-Disposition: form-data; name="password"

superSecret123
--BOUNDARY--

### 4) USERPROFILE

# use user id from register or login
POST {{baseUrl}}/profile/GWpmbk5ezJn4 

### 5) PUBLICFEED

# use user id from register or login
GET {{baseUrl}}/public-feed 

### 5) FOLLOW SUGGESTIONS
GET {{baseUrl}}/users/follow-suggestions

### 6) USER GROUPS
POST {{baseUrl}}/groups/user/
Content-Type: application/json

{
  "limit": 10,
  "offset": 0
}

### 7) CHANGE PASSWORD
POST {{baseUrl}}/account/update/password
Content-Type: application/json

{
  "old_password": "superSecret1234",
  "new_password": "superSecret123"
}