@baseUrl = http://localhost:8081
@token= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNzgxNTk2NTk1LCJpYXQiOjE3NjU4NzE3OTV9.t26_Z2z_7PbcCo232SlQIIo1maR7nPJ8o627yybHGkw"

### 1) LOGIN
POST {{baseUrl}}/login
Content-Type: application/json

{
  "identifier": "myuser1234",
  "password": "superSecret123"
}

### 2) LOGOUT
POST {{baseUrl}}/logout
Content-Type: application/json

### 3) REGISTER (multipart form-data)
POST {{baseUrl}}/register
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="username"

user123
--BOUNDARY
Content-Disposition: form-data; name="first_name"

John
--BOUNDARY
Content-Disposition: form-data; name="last_name"

Doe
--BOUNDARY
Content-Disposition: form-data; name="date_of_birth"

1999-01-01
--BOUNDARY
Content-Disposition: form-data; name="about"

I love coding!
--BOUNDARY
Content-Disposition: form-data; name="public"

true
--BOUNDARY
Content-Disposition: form-data; name="email"

user123@example.com
--BOUNDARY
Content-Disposition: form-data; name="password"

superSecret1234
--BOUNDARY--

### 4) USERPROFILE

# use user id from register or login
POST {{baseUrl}}/profile/GWpmbk5ezJn4 


### 5) FOLLOW SUGGESTIONS
POST {{baseUrl}}/users/follow-suggestions

### 6) USER GROUPS
POST {{baseUrl}}/groups/user/
Content-Type: application/json

{
  "limit": 10,
  "offset": 0
}

### 7) CHANGE PASSWORD
POST {{baseUrl}}/account/update/password
Content-Type: application/json

{
  "old_password": "superSecret1234",
  "new_password": "superSecret123"
}

### GET POST BY ID
POST {{baseUrl}}/post/
Content-Type: application/json

{
  "entity_id": 1,
}

### CREATE POST
POST {{baseUrl}}/posts/create
Content-Type: application/json

{
	"body": "What a glorious day",
	"audience":"everyone"
	
}

### DELETE POST
POST {{baseUrl}}/posts/delete/
Content-Type: application/json

{
  "entity_id": ,
}

###  PUBLICFEED

# use user id from register or login
POST {{baseUrl}}/public-feed 
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "limit": 10,
  "offset": 0
}